"""golfprice_email_block.py - optional "golfprice model scorecard" block for the Monday results email.

Owner-approved production change (October 5, 2026). The golfprice research system publishes a weekly scorecard to the dashboard's R2 bucket
(golf-model-dashboard-data, key golfprice/scorecard/latest.json). monday_grading.py calls prepare_env() once before grading; it reads that object
with the credentials the workflow already has (CF_ACCOUNT_ID + DASHBOARD_R2_ACCESS_KEY_ID / DASHBOARD_R2_SECRET_ACCESS_KEY), renders a short HTML
block and hands it to grade_bets.send_results_email through the environment variable GOLFPRICE_EMAIL_BLOCK_HTML, which inserts it before the
footer of the results email.

Fail-safe by construction: any error, a missing object, a bad schema, or a file older than MAX_AGE_DAYS (8) yields no block and ONE log line.
Nothing here raises to the caller, writes to R2, Sheets or Git, or changes grading, publishing or the rest of the email. Credentials are never printed.
"""
from __future__ import annotations

import datetime as dt
import html as _html
import json
import os

BUCKET_DEFAULT = "golf-model-dashboard-data"
KEY = "golfprice/scorecard/latest.json"
SCHEMA = "golfprice.scorecard.v1"
MAX_AGE_DAYS = 8
ENV_VAR = "GOLFPRICE_EMAIL_BLOCK_HTML"
FOOTER_MARKER = "Generated by Golf Sim Bet Tracker"
MARKETS = [("win", "Win"), ("top_5", "Top 5"), ("top_10", "Top 10"), ("top_20", "Top 20"), ("make_cut", "Make cut")]
MAX_HEADLINES = 6
MAX_ARM_ROWS = 6


def _log(msg):
    print(f"  golfprice email block: {msg}")


def _r2_client():
    """Same construction as cloudflare_dashboard/scripts/publish_dashboard_data.py (_r2_client), plus short timeouts and no retries."""
    import boto3
    from botocore.config import Config

    account_id = os.environ["CF_ACCOUNT_ID"]
    access_key = os.getenv("DASHBOARD_R2_ACCESS_KEY_ID") or os.environ["R2_ACCESS_KEY_ID"]
    secret_key = os.getenv("DASHBOARD_R2_SECRET_ACCESS_KEY") or os.environ["R2_SECRET_ACCESS_KEY"]
    return boto3.client(
        "s3",
        endpoint_url=f"https://{account_id}.r2.cloudflarestorage.com",
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        region_name="auto",
        config=Config(connect_timeout=5, read_timeout=10, retries={"max_attempts": 1}),
    )


def fetch_scorecard(client=None, bucket=None, key=KEY):
    """The parsed scorecard document. Raises on any problem (the callers below contain it)."""
    client = client or _r2_client()
    bucket = bucket or os.getenv("DASHBOARD_R2_BUCKET") or BUCKET_DEFAULT
    body = client.get_object(Bucket=bucket, Key=key)["Body"].read()
    doc = json.loads(body.decode("utf-8"))
    if not isinstance(doc, dict) or doc.get("schema") != SCHEMA:
        raise ValueError("unexpected scorecard schema")
    return doc


def age_days(doc, now=None):
    now = now or dt.datetime.now(dt.timezone.utc)
    stamp = dt.datetime.strptime(str(doc["generated_at"]), "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=dt.timezone.utc)
    return (now - stamp).total_seconds() / 86400.0


def _esc(x):
    return _html.escape("" if x is None else str(x))


def _num(x, nd=3, sign=True):
    if x is None or isinstance(x, bool) or not isinstance(x, (int, float)):
        return "-"
    return f"{x:+.{nd}f}" if sign else f"{x:.{nd}f}"


def _color(x):
    """Negative is better for every delta in the scorecard."""
    if not isinstance(x, (int, float)) or x == 0:
        return "#333"
    return "#28a745" if x < 0 else "#dc3545"


def render_block(doc):
    """Short HTML block (inline styles like the rest of the email): headline lines plus one small table of the latest week by arm."""
    fwd = doc.get("forward") or {}
    heads = [h for h in (doc.get("headlines") or []) if isinstance(h, str)][:MAX_HEADLINES]
    events = {e.get("event_uid"): e for e in (doc.get("events") or []) if isinstance(e, dict)}
    lw = [events[u] for u in ((doc.get("latest_week") or {}).get("event_uids") or []) if u in events]
    ev = next((e for e in lw if e.get("tour") == "pga"), lw[0] if lw else None)
    parts = [
        '<div style="margin:24px 0; padding:16px; background:#f7fafc; border:1px solid #e2e8f0; border-radius:8px;">',
        '<h3 style="color:#2c5282; margin:0 0 10px 0; border-bottom:2px solid #e2e8f0; padding-bottom:8px;">golfprice model scorecard (research, not staked)</h3>',
        '<ul style="margin:0 0 12px 18px; padding:0; font-size:13px; color:#333; line-height:1.5;">',
    ]
    parts += [f"<li>{_esc(h)}</li>" for h in heads]
    parts.append("</ul>")
    if ev and ev.get("arms"):
        parts.append(f'<div style="font-size:12px; color:#666; margin-bottom:6px;">{_esc(ev.get("name"))} ({_esc(str(ev.get("tour", "")).upper())}, {_esc(ev.get("event_start"))}); negative is better than the production model</div>')
        parts.append('<table style="width:100%; border-collapse:collapse; font-size:12px;">')
        parts.append('<tr style="background:#edf2f7;"><th style="padding:6px 8px; text-align:left;">Arm</th><th style="padding:6px 8px; text-align:center;">Skill error</th>'
                     '<th style="padding:6px 8px; text-align:center;">vs prod</th><th style="padding:6px 8px; text-align:center;">Finish log-loss vs prod</th>'
                     '<th style="padding:6px 8px; text-align:center;">vs close</th></tr>')
        for a in [a for a in ev["arms"] if isinstance(a, dict)][:MAX_ARM_ROWS]:
            base = a.get("arm") == "champion"
            d1, d2, d3 = a.get("rmse_vs_champion"), a.get("logloss_vs_champion_mean"), a.get("logloss_vs_close_mean")
            parts.append(
                f'<tr><td style="padding:6px 8px; border-top:1px solid #e2e8f0;">{_esc(a.get("label") or a.get("arm"))}</td>'
                f'<td style="padding:6px 8px; text-align:center; border-top:1px solid #e2e8f0;">{_num(a.get("rmse"), 3, False)}</td>'
                f'<td style="padding:6px 8px; text-align:center; border-top:1px solid #e2e8f0; color:{_color(d1)};">{"baseline" if base else _num(d1, 3)}</td>'
                f'<td style="padding:6px 8px; text-align:center; border-top:1px solid #e2e8f0; color:{_color(d2)};">{"-" if base else _num(d2, 4)}</td>'
                f'<td style="padding:6px 8px; text-align:center; border-top:1px solid #e2e8f0; color:{_color(d3)};">{_num(d3, 4)}</td></tr>')
        parts.append("</table>")
    n, fut = fwd.get("events_counted"), fwd.get("futility_check_at")
    if isinstance(n, int) and isinstance(fut, int):
        parts.append(f'<div style="font-size:11px; color:#999; margin-top:8px;">Forward record: {n} of {fut} events toward the futility check. Generated {_esc(doc.get("generated_at"))}.</div>')
    parts.append("</div>")
    return "".join(parts)


def build_block(client=None, now=None, log=_log):
    """The block HTML, or "" (with one log line) on any problem or when the scorecard is stale. Never raises."""
    try:
        doc = fetch_scorecard(client=client)
        age = age_days(doc, now)
        if age > MAX_AGE_DAYS:
            log(f"skipped: scorecard is {age:.1f} days old (limit {MAX_AGE_DAYS})")
            return ""
        return render_block(doc)
    except Exception as exc:  # noqa: BLE001 - fail-safe: the email and grading must never depend on this
        log(f"skipped: {type(exc).__name__}")
        return ""


def prepare_env(environ=None, client=None, now=None, log=_log):
    """Called once by monday_grading.py before grading: put the block in the environment for the grade_bets.py subprocess. Never raises."""
    try:
        environ = os.environ if environ is None else environ
        block = build_block(client=client, now=now, log=log)
        if block:
            environ[ENV_VAR] = block
            log("block ready for the results email")
            return True
    except Exception as exc:  # noqa: BLE001
        try:
            log(f"skipped: {type(exc).__name__}")
        except Exception:  # noqa: BLE001
            pass
    return False


def inject(html, block):
    """Insert `block` before the email footer paragraph (else before </body>, else at the end). Returns `html` unchanged when there is no block."""
    if not block:
        return html
    i = html.find(FOOTER_MARKER)
    if i != -1:
        j = html.rfind("<p", 0, i)
        if j != -1:
            return html[:j] + block + html[j:]
    k = html.lower().rfind("</body>")
    return html[:k] + block + html[k:] if k != -1 else html + block


def with_block(html, environ=None):
    """grade_bets.send_results_email hook: the email HTML with the prepared block inserted (unchanged on any problem)."""
    try:
        environ = os.environ if environ is None else environ
        return inject(html, environ.get(ENV_VAR, ""))
    except Exception:  # noqa: BLE001
        return html
