"use client";
import {useDashboardData} from "./data";
import {parseDeep,finite,type DeepProfile} from "./player-deep-rules";
import {playerId,profileKey,PROFILE_AXES,type PlayerProfile} from "./player-profile-rules";
import {filteredShotMetrics,filteredSkillProfile,sliceHistory,type HistoryFilters,type ShotReference,type ObservedCategoryReference} from "./player-history-filters";
import {ShotDetailsShape} from "./PlayerDeepDive";
const colors=["var(--chart-1)","var(--chart-2)","var(--chart-3)"];
const labels=["Off the tee","Approach","Around green","Putting"];
const signed=(v:unknown)=>finite(v)?`${v>0?"+":""}${v.toFixed(2)}`:"—";
export function FilteredPlayerShapes({profile,deep,comparisons,filters,reference,categoryReference}:{profile:PlayerProfile;deep:DeepProfile|null;comparisons:PlayerProfile[];filters:HistoryFilters;reference:ShotReference;categoryReference?:ObservedCategoryReference}){
 const first=useDashboardData<unknown>(profileKey(comparisons[0]?.deep_key??"fields.json")),second=useDashboardData<unknown>(profileKey(comparisons[1]?.deep_key??"fields.json"));
 const active={...filters,asOf:deep?.as_of},events=sliceHistory(deep?.history?.events??[],active),shots=filteredShotMetrics(deep,events,reference);
 const own=filteredSkillProfile(profile,events,categoryReference),profiles=[own,...comparisons.flatMap((p,i)=>{const d=parseDeep(i===0?first.data:second.data,playerId(p.identity));return d&&d.as_of===deep?.as_of?[filteredSkillProfile(p,sliceHistory(d.history?.events??[],active),categoryReference)]:[];})];
 const point=(i:number,r:number)=>{const a=(i*90-90)*Math.PI/180;return [210+Math.cos(a)*125*r,178+Math.sin(a)*125*r];},polygon=(r:number)=>[0,1,2,3].map(i=>point(i,r).join(",")).join(" "),radius=(v:number)=>.5+Math.max(-3,Math.min(3,v))/6;
 const filteredDeep=deep?{...deep,shots:deep.shots?{...deep.shots,metrics:shots.metrics}:null}:null;
 return <><div className="pd-shape-scope"><b>Observed shape · selected rounds</b><span>Same filters as the event record. Fixed reference populations; no model refit or shrinkage.</span></div><div className="pp-shapes"><div><h3>Strokes-gained shape</h3><svg className="pp-radar" viewBox="0 0 420 355" role="img" aria-label="Filtered observed field-relative strokes gained categories, standardized against the published raw observed PGA category reference. Exact values below.">
 {[.25,.5,.75,1].map(r=><polygon key={r} points={polygon(r)} fill="none" stroke={r===.5?"var(--muted)":"var(--line)"} strokeDasharray={r===.5?"5 4":undefined}/>)}
 {PROFILE_AXES.map((k,i)=>{const end=point(i,1),label=point(i,1.27);return <g key={k}><line x1="210" y1="178" x2={end[0]} y2={end[1]} stroke="var(--line)"/><text x={label[0]} y={label[1]} textAnchor="middle" fill="var(--muted-strong)" fontSize="12">{labels[i]}</text></g>;})}
 {profiles.map((p,j)=><g key={playerId(p.identity)}>{p.radar.every(m=>finite(m.z))&&<polygon points={PROFILE_AXES.map((k,i)=>point(i,radius(p.radar.find(m=>m.key===k)!.z!)).join(",")).join(" ")} fill={colors[j]} fillOpacity=".08" stroke={colors[j]} strokeWidth="2" strokeDasharray={j?"5 4":undefined}/>} {PROFILE_AXES.map((k,i)=>{const m=p.radar.find(m=>m.key===k);if(!finite(m?.z))return null;const xy=point(i,radius(m.z));return <circle key={k} cx={xy[0]} cy={xy[1]} r="4" fill={colors[j]}><title>{p.identity.name}: {m.label} {signed(m.z)} Z, {m.n} selected rounds</title></circle>;})}</g>)}<text x="216" y="49" fill="var(--muted)" fontSize="10">+3 Z</text><text x="216" y="178" fill="var(--muted)" fontSize="10">−3 Z</text><text x="216" y="111" fill="var(--muted)" fontSize="10">0 Z</text></svg>
 <div className="pp-legend">{profiles.map((p,i)=><span key={playerId(p.identity)}><i style={{background:colors[i]}}/>{p.identity.name}</span>)}</div><p className="pd-muted">Observed field-relative category means in the selected slice. Fixed PGA means and standard deviations of unshrunk player category averages set the axes; no new skill estimate is fitted. Cross-tour quality and opportunity mix remain. At least three covered rounds per axis; sparse slices are exploratory. Drawing clips at ±3 Z; exact Z values appear below. Comparison players follow the same filters on their own schedules.</p>
 </div><div><ShotDetailsShape deep={filteredDeep} filtered/><p className="pd-shape-coverage" role="status">{shots.available?`${shots.n_rounds} selected rounds have published shot detail in the trailing three-year window.`:"Round-linked shot detail has not been published for this profile; no filtered fingerprint is shown."} Radar reference stays fixed across slices.</p></div></div>
 <div className="pd-scroll"><table className="pd-table"><caption>Observed category SG / round · fixed observed PGA reference · selected rounds only</caption><thead><tr><th>Category</th>{profiles.map(p=><th key={playerId(p.identity)}>{p.identity.name}<small>Mean / rounds / Z</small></th>)}</tr></thead><tbody>{PROFILE_AXES.map((k,i)=><tr key={k}><th scope="row">{labels[i]}</th>{profiles.map(p=>{const m=p.radar.find(m=>m.key===k);return <td key={playerId(p.identity)}>{signed(m?.value)}<small>{m?.n??0} rounds · {signed(m?.z)} Z</small></td>;})}</tr>)}</tbody></table></div><details className="pd-method"><summary>Observed PGA reference and support</summary><p>This reference uses unweighted player averages of published field-relative category SG over the trailing three years. A player needs at least 20 finite rounds per category. Every qualifying PGA player has equal weight; no shrinkage, recency decay or additional course centering is applied. The reference stays fixed when filters change.</p>{PROFILE_AXES.map((k,i)=>{const r=categoryReference?.axes[k];return <p key={k}>{labels[i]}: mean {signed(r?.mean)} SG/round · SD {signed(r?.sd)} · {r?.n_players??0} PGA players.</p>;})}<p>Reference: {categoryReference?.id??"unavailable"}. Selected player means may come from much smaller samples and are not latent skill estimates.</p></details></>;
}
