"use client";
import {useDashboardData} from "./data";
import {parseDeep,finite,GLOSS,type DeepProfile} from "./player-deep-rules";
import {playerId,profileKey,PROFILE_AXES,type PlayerProfile} from "./player-profile-rules";
import {filteredShotMetrics,filteredSkillProfile,hasSituationFilters,playerBaselineFilters,sliceHistory,type HistoryFilters,type ShotReference,type ObservedCategoryReference} from "./player-history-filters";
import {ShotDetailsShape} from "./PlayerDeepDive";
const colors=["var(--chart-1)","var(--chart-2)","var(--chart-3)"];
const labels=["Off the tee","Approach","Around green","Putting"];
const labelHelp=[GLOSS.sgOtt,GLOSS.sgApp,GLOSS.sgArg,GLOSS.sgPutt];
const signed=(v:unknown)=>finite(v)?`${v>0?"+":""}${v.toFixed(2)}`:"—";
export function FilteredPlayerShapes({profile,deep,comparisons,filters,reference,categoryReference}:{profile:PlayerProfile;deep:DeepProfile|null;comparisons:PlayerProfile[];filters:HistoryFilters;reference:ShotReference;categoryReference?:ObservedCategoryReference}){
 const first=useDashboardData<unknown>(profileKey(comparisons[0]?.deep_key??"fields.json")),second=useDashboardData<unknown>(profileKey(comparisons[1]?.deep_key??"fields.json"));
 const active={...filters,asOf:deep?.as_of},events=sliceHistory(deep?.history?.events??[],active),shots=filteredShotMetrics(deep,events,reference);
 const showBaseline=hasSituationFilters(active),baselineEvents=sliceHistory(deep?.history?.events??[],playerBaselineFilters(active)),baseline=filteredSkillProfile(profile,baselineEvents,categoryReference),baselineShots=filteredShotMetrics(deep,baselineEvents,reference);
 const own=filteredSkillProfile(profile,events,categoryReference),profiles=[own,...comparisons.flatMap((p,i)=>{const d=parseDeep(i===0?first.data:second.data,playerId(p.identity));return d&&d.as_of===deep?.as_of?[filteredSkillProfile(p,sliceHistory(d.history?.events??[],active),categoryReference)]:[];})];
 const point=(i:number,r:number)=>{const a=(i*90-90)*Math.PI/180;return [210+Math.cos(a)*125*r,178+Math.sin(a)*125*r];},polygon=(r:number)=>[0,1,2,3].map(i=>point(i,r).join(",")).join(" "),radius=(v:number)=>.5+Math.max(-3,Math.min(3,v))/6;
 const filteredDeep=deep?{...deep,shots:deep.shots?{...deep.shots,metrics:shots.metrics}:null}:null;
 return <><div className="pd-shape-scope"><b>Skill shape for the selected rounds</b><span>Uses the same filters as the event record.{showBaseline&&" The dashed line is this player’s overall baseline for the same period, across all rounds and situations."}</span></div><div className="pp-shapes"><div><h3>Strokes-gained shape</h3><svg className="pp-radar" viewBox="0 0 420 355" role="img" aria-label={`Strokes gained by category for the selected rounds, compared with the PGA average.${showBaseline?" The dashed overlay shows this player’s overall baseline for the same period.":""} Exact values are in the table below.`}>
 {[.25,.5,.75,1].map(r=><polygon key={r} points={polygon(r)} fill="none" stroke={r===.5?"var(--muted)":"var(--line)"} strokeDasharray={r===.5?"5 4":undefined}/>)}
 {PROFILE_AXES.map((k,i)=>{const end=point(i,1),label=point(i,1.27);return <g key={k}><line x1="210" y1="178" x2={end[0]} y2={end[1]} stroke="var(--line)"/><text x={label[0]} y={label[1]} textAnchor="middle" fill="var(--muted-strong)" fontSize="12">{labels[i]}</text></g>;})}
 {showBaseline&&<g data-player-baseline="sg">{baseline.radar.every(m=>finite(m.z))&&<polygon points={PROFILE_AXES.map((k,i)=>point(i,radius(baseline.radar.find(m=>m.key===k)!.z!)).join(",")).join(" ")} fill="var(--muted-strong)" fillOpacity=".04" stroke="var(--muted-strong)" strokeWidth="2" strokeDasharray="9 5"/>}{PROFILE_AXES.map((k,i)=>{const m=baseline.radar.find(m=>m.key===k);if(!finite(m?.z))return null;const xy=point(i,radius(m.z));return <circle key={k} cx={xy[0]} cy={xy[1]} r="4" fill="var(--surface)" stroke="var(--muted-strong)" strokeWidth="1.5"><title>Player baseline: {m.label} {signed(m.z)} SDs vs PGA, {m.n} rounds</title></circle>;})}</g>}
 {profiles.map((p,j)=><g key={playerId(p.identity)}>{p.radar.every(m=>finite(m.z))&&<polygon points={PROFILE_AXES.map((k,i)=>point(i,radius(p.radar.find(m=>m.key===k)!.z!)).join(",")).join(" ")} fill={colors[j]} fillOpacity=".08" stroke={colors[j]} strokeWidth="2" strokeDasharray={j?"5 4":undefined}/>} {PROFILE_AXES.map((k,i)=>{const m=p.radar.find(m=>m.key===k);if(!finite(m?.z))return null;const xy=point(i,radius(m.z));return <circle key={k} cx={xy[0]} cy={xy[1]} r="4" fill={colors[j]}><title>{p.identity.name}: {m.label} {signed(m.z)} SDs vs PGA, {m.n} selected rounds</title></circle>;})}</g>)}<text x="216" y="49" fill="var(--muted)" fontSize="10">+3 SDs</text><text x="216" y="178" fill="var(--muted)" fontSize="10">−3 SDs</text><text x="216" y="111" fill="var(--muted)" fontSize="10">PGA average</text></svg>
 <div className="pp-legend">{showBaseline&&<span><i style={{background:"var(--muted-strong)"}}/>Player’s overall baseline (dashed)</span>}{profiles.map((p,i)=><span key={playerId(p.identity)}><i style={{background:colors[i]}}/>{p.identity.name}</span>)}</div><p className="pd-muted">How far this player’s average in each category sits from the PGA average, in standard deviations (SDs). Categories with fewer than three rounds are left off.</p><details className="pd-method"><summary>How this is calculated</summary><p>Each axis compares the player’s average strokes gained per round in the selected rounds with the average and spread of PGA players over the last three years. Nothing is re-fitted or smoothed, so small samples swing a lot. The chart is clipped at ±3 SDs. Comparison players use the same filters on their own schedules. Quality of competition and the mix of opportunities are not adjusted for.</p></details>
 </div><div><ShotDetailsShape deep={filteredDeep} filtered baselineMetrics={showBaseline?baselineShots.metrics:undefined}/><p className="pd-shape-coverage" role="status">{shots.available?`${shots.n_rounds} selected rounds have published shot detail (last three years).`:"Shot detail by round is not published for this player, so no shot fingerprint is shown for the selected rounds."}</p></div></div>
 <div className="pd-scroll"><table className="pd-table"><caption>Strokes gained per round for the selected rounds{showBaseline&&", next to the player’s overall baseline"}</caption><thead><tr><th>Category</th>{showBaseline&&<th title="This player across all rounds and situations in the same period.">Player baseline<small title={GLOSS.sd}>Average · rounds · vs PGA (SDs)</small></th>}{profiles.map(p=><th key={playerId(p.identity)}>{p.identity.name}<small title={GLOSS.sd}>Average · rounds · vs PGA (SDs)</small></th>)}</tr></thead><tbody>{PROFILE_AXES.map((k,i)=><tr key={k}><th scope="row" title={labelHelp[i]}>{labels[i]}</th>{showBaseline&&<td>{signed(baseline.radar.find(m=>m.key===k)?.value)}<small>{baseline.radar.find(m=>m.key===k)?.n??0} rounds · {signed(baseline.radar.find(m=>m.key===k)?.z)} SDs</small></td>}{profiles.map(p=>{const m=p.radar.find(m=>m.key===k);return <td key={playerId(p.identity)}>{signed(m?.value)}<small>{m?.n??0} rounds · {signed(m?.z)} SDs</small></td>;})}</tr>)}</tbody></table></div><details className="pd-method"><summary>Technical details</summary><p>The PGA average and spread come from each qualifying PGA player’s average over the last three years (at least 20 rounds per category, every player weighted equally, no smoothing). They stay fixed when the filters change. Selected-round averages can come from much smaller samples and are not skill estimates.</p>{PROFILE_AXES.map((k,i)=>{const r=categoryReference?.axes[k];return <p key={k}>{labels[i]}: PGA average {signed(r?.mean)} per round, spread (SD) {finite(r?.sd)?r.sd.toFixed(2):"n/a"}, {r?.n_players??0} players.</p>;})}<p>Reference: {categoryReference?.id??"unavailable"}.</p></details></>;
}
