"use client";

import {Fragment, useMemo, useState} from "react";
import {Panel} from "./components";
import {useDashboardData} from "./data";
import {profileKey, playerId, type PlayerProfile} from "./player-profile-rules";
import {DEFAULT_FILTERS, EVENT_METRICS, commonEventSlices, centeredValues, evidenceSlice, eventMetricValue, exploratoryStandouts, openingContext, distributionSummary, filterEvents, finite, formatMetric,
  histogram, parseDeep, roundValues, shapePoints, sortEvents,
  type DeepProfile, type EventFilters, type EventMetric, type ShotMetric} from "./player-deep-rules";
import "./player-deep.css";
import {PerformanceTrend} from "./PlayerPerformanceTrend";

const date=(v:string|undefined)=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}):"Unavailable";
const signed=(v:unknown)=>finite(v)?`${v>0?"+":""}${v.toFixed(2)}`:"—";
const fraction=(v:unknown)=>finite(v)?`${(v*100).toFixed(1)}%`:"—";
const groups={
  "All-round detail":["tee_distance","tee_accuracy","tee_dispersion","app_great","app_150_200","arg_rough"],
  "Driving":["tee_distance","tee_accuracy","tee_dispersion","tee_sg","tee_great","tee_poor"],
  "Putting":["putt_0_5","putt_5_10","putt_10_20","putt_20_plus","putt_short_make","putt_lag_leave"],
  "Approach":["app_50_100","app_100_150","app_150_200","app_200_plus","app_great","prox_rough"],
  "Short game":["arg_sand","arg_rough","arg_fairway","prox_fairway","prox_rough","app_poor"],
};
const axisLabel:Record<string,string>={tee_sg:"Tee SG",tee_great:"Great tee",tee_poor:"Poor avoidance",putt_0_5:"<5 ft SG",putt_5_10:"5–10 ft SG",putt_10_20:"10–20 ft SG",putt_20_plus:"20+ ft SG",putt_short_make:"<5 ft makes",putt_lag_leave:"Lag leave",tee_distance:"Distance",tee_accuracy:"Fairways",tee_dispersion:"Dispersion",app_great:"Great APP",app_poor:"Poor avoidance",app_50_100:"50–100",app_100_150:"100–150",app_150_200:"150–200",app_200_plus:"200+",arg_sand:"Bunker",arg_rough:"Rough ARG",arg_fairway:"Fairway ARG",prox_fairway:"FW proximity",prox_rough:"Rough proximity"};

export function ShotDetailsShape({deep}:{deep:DeepProfile|null}){
  const [group,setGroup]=useState<keyof typeof groups>("All-round detail");
  const metrics=deep?.shots?.metrics??[];
  const keys=groups[group];const shape=shapePoints(metrics,keys);
  const point=(i:number,r:number)=>{const a=(i*60-90)*Math.PI/180;return [190+Math.cos(a)*106*r,158+Math.sin(a)*106*r];};
  const polygon=(r:number)=>keys.map((_,i)=>point(i,r).join(",")).join(" ");
  const strong=exploratoryStandouts(metrics,keys);
  return <div className="pd-shot"><div className="pd-heading"><div><span className="eyebrow">The details behind the score</span><h3>Shot fingerprint</h3></div><label className="pd-select"><span className="sr-only">Shot fingerprint axes</span><select value={group} onChange={e=>setGroup(e.target.value as keyof typeof groups)}>{Object.keys(groups).map(k=><option key={k}>{k}</option>)}</select></label></div>
    {!metrics.length?<p className="pd-empty">Published shot detail is unavailable for this player. Feeder and amateur results can still appear in event history.</p>:<>
      <svg className="pd-fingerprint" viewBox="0 0 380 326" role="img" aria-label="Observed shot detail relative to supported PGA players. Higher is better on every axis. Missing values have no point; exact values below.">
        {[.25,.5,.75,1].map(r=><polygon key={r} points={polygon(r)} fill="none" stroke={r===.5?"var(--muted)":"var(--line)"} strokeDasharray={r===.5?"4 4":undefined}/>)}
        {keys.map((k,i)=>{const end=point(i,1),label=point(i,1.34);return <g key={k}><line x1="190" y1="158" x2={end[0]} y2={end[1]} stroke="var(--line)"/><text x={label[0]} y={label[1]} textAnchor="middle" fill="var(--muted-strong)" fontSize="11">{axisLabel[k]}</text></g>;})}
        {shape.complete&&<polygon points={shape.radii.map((r,i)=>point(i,r!).join(",")).join(" ")} fill="var(--chart-2)" fillOpacity=".12" stroke="var(--chart-2)" strokeWidth="2"/>}
        {shape.radii.map((r,i)=>r===null?null:<circle key={keys[i]} cx={point(i,r)[0]} cy={point(i,r)[1]} r="4" fill="var(--chart-2)"><title>{metrics.find(m=>m.key===keys[i])?.label}: {signed(metrics.find(m=>m.key===keys[i])?.reference_z)} Z; higher is better</title></circle>)}
        <text x="196" y="101" fill="var(--muted)" fontSize="10">PGA mean</text>
      </svg><div className="pd-shot-values">{keys.map(k=>{const m=metrics.find(v=>v.key===k);return <div key={k}><span>{k==="tee_poor"?"Poor tee rate":k==="app_poor"?"Poor APP rate":axisLabel[k]}</span><b>{formatMetric(m?.value,m?.unit??"")}</b><small>{m?.unit==="fraction"?"rate":m?.unit??"Unavailable"}{m?.higher_is_better===false?" · lower is better":""} · {m?.n_shots??0} shots · PGA n={m?.reference_n_players??"?"}{m?.status!=="available"||(m?.n_shots??0)<100||(m?.n_rounds??0)<10?" · provisional":""}</small></div>;})}</div><p className="pd-muted">{strong.length?<>Exploratory strengths among these axes: <b>{strong.map(m=>m.label.toLowerCase()).join(" · ")}</b>. </>:null}Each axis is standardized separately against its own supported PGA cohort; higher is better. The connected area is not a composite skill score. Opportunity mix remains. Dashed ring = each metric’s cohort mean. {shape.complete?"":"Partial sample: available points only. "}Display clips at ±2.5 standard deviations. Reference as of {date(metrics.find(m=>m.reference_as_of)?.reference_as_of)}; published trailing 3 years. Tee distance includes all clubs; dispersion is around the field landing axis, not the target. {group==="Driving"&&"Tee-shot outcomes exclude separate penalty/drop records; poor-shot rate is not all driving trouble."}{group==="Putting"&&"Putting buckets use feet. Short-putt make rate and lag leave distance retain the actual distance mix; they are not fixed-distance probabilities or three-putt rates."}</p>
      <details className="pd-method"><summary>Exact shot metrics · {metrics.filter(m=>m.status==="available").length}/{metrics.length} supported</summary><div className="pd-scroll"><table className="pd-table"><caption>Observed outcomes; metrics use different opportunities and do not add to total SG.</caption><thead><tr><th>Metric</th><th>Value</th><th>Shots / rounds</th><th>PGA rank</th></tr></thead><tbody>{metrics.map(m=><MetricRow key={m.key} metric={m}/>)}</tbody></table></div><p className="pd-muted">{String(deep?.shots?.coverage?.eligible_shots??"Unknown")} eligible physical shots · {String(deep?.shots?.coverage?.complete_rounds??"unknown")} rounds with eligible shots · through {date(String(deep?.shots?.coverage?.last_date??""))}. Excluded records: {String(deep?.shots?.coverage?.excluded_shots??"unavailable")}. {String(deep?.shots?.coverage?.note??"")}</p><p className="pd-muted">Ranks compare descriptive metrics with PGA players having ≥100 shots and ≥10 rounds in the same metric. No rank is shown without a supported cohort. Course, starting lie and distance mix remain. Distance uses all clubs on par 4/5 tees. Dispersion is around the field landing axis, not the intended target. A measured driver-only record is unavailable.</p></details>
    </>}
  </div>;
}

function MetricRow({metric:m}:{metric:ShotMetric}){return <tr><th scope="row"><details><summary>{m.label}</summary><p>{m.definition}</p><small>Last observation {date(m.last_date)}</small></details></th><td>{formatMetric(m.value,m.unit)}<small>{m.unit==="fraction"?"rate":m.unit}{m.status!=="available"?` · ${m.status?.replaceAll("_"," ")??"unsupported"}`:""}</small></td><td>{m.n_shots??0} / {m.n_rounds??0}</td><td>{m.status==="available"&&finite(m.reference_percentile)?`${Math.round(m.reference_percentile*100)}th${(m.n_shots??0)<100||(m.n_rounds??0)<10?" · provisional":""}`:"—"}<small>{finite(m.reference_n_players)?`PGA n=${m.reference_n_players}`:"Cohort size unavailable"}</small></td></tr>;}

function BaselineChart({deep}:{deep:DeepProfile}){
  const b=deep.baseline,series=(b?.series??[]).filter(p=>finite(p.value)&&Number.isFinite(Date.parse(p.date)));
  if(!series.length)return <p className="pd-empty">A course-neutral legacy baseline history is unavailable for this player.</p>;
  const times=series.map(p=>Date.parse(p.date)),left=Math.min(...times),right=Math.max(...times);
  const values=series.flatMap(p=>[p.value,...(finite(p.moving_average_90d)?[p.moving_average_90d]:[])]);
  const low=Math.min(-.25,...values)-.2,high=Math.max(.25,...values)+.2;
  const x=(t:number)=>52+(t-left)/Math.max(1,right-left)*680,y=(v:number)=>185-(v-low)/(high-low)*145;
  const line=(key:"value"|"moving_average_90d")=>series.filter(p=>finite(p[key])).map(p=>`${x(Date.parse(p.date))},${y(p[key]!)}`).join(" ");
  return <><div className="pd-baseline-head"><div><span className="eyebrow">Course-neutral legacy model</span><strong>{signed(b?.value)} <small>SG/round vs fixed PGA reference</small></strong></div><span className="pd-tag">Latest {date(b?.latest_date)}</span></div>
    <svg className="pd-line" viewBox="0 0 780 225" role="img" aria-label="Legacy published course-neutral model skill over time with a trailing 90-day moving average. Reconstructed from revised history, not archived forecasts.">
      {[low,(low+high)/2,high].map(v=><g key={v}><line x1="52" y1={y(v)} x2="732" y2={y(v)} stroke="var(--line)"/><text x="42" y={y(v)+4} textAnchor="end" fill="var(--muted)" fontSize="11">{signed(v)}</text></g>)}
      <line x1="52" x2="732" y1={y(0)} y2={y(0)} stroke="var(--muted)" strokeDasharray="4 4"/>
      <polyline points={line("value")} fill="none" stroke="var(--chart-1)" strokeOpacity=".45" strokeWidth="1.5"/>
      <polyline points={line("moving_average_90d")} fill="none" stroke="var(--chart-2)" strokeWidth="2.5"/>
      {series.length===1&&<circle cx={x(times[0])} cy={y(series[0].value)} r="4" fill="var(--chart-1)"/>}
      <text x="52" y="215" fill="var(--muted)" fontSize="11">{date(series[0].date)}</text><text x="732" y="215" textAnchor="end" fill="var(--muted)" fontSize="11">{date(series[series.length-1].date)}</text>
    </svg><div className="pd-legend"><span><i style={{background:"var(--chart-1)",opacity:.5}}/>Saved legacy estimate</span><span><i style={{background:"var(--chart-2)"}}/>Trailing 90-day average</span></div><p className="pd-muted">Retrospective monthly observations from our revised legacy published skill estimate; latest observation {date(b?.latest_date)}. The curve is sampled monthly, while its 90-day average uses saved daily observations. No course-specific adjustment. The current golfprice CHL pricing model uses a different estimator. This reconstructed, revised history is not an immutable record of forecasts made on those dates.</p><details className="pd-method"><summary>Baseline provenance and moving average</summary>{b?.limitations?.map((s,i)=><p key={i}>{s}</p>)}<p>Points show the last saved daily estimate each month. The 90-day line averages saved daily observations, rather than averaging the displayed monthly points. Reference: {b?.reference_id??"unavailable"}.</p></details></>;
}

function RoundDistribution({deep,events,all,center}:{deep:DeepProfile;events:NonNullable<DeepProfile["history"]>["events"];all:boolean;center:boolean}){
  const values=roundValues(events,all),summary=distributionSummary(values),slice=evidenceSlice(events,all),bins=histogram(centeredValues(values,center)),max=Math.max(1,...bins.map(b=>b.count));
  return <><p className="pd-sample"><b>{slice.n_events} events · {summary.n} adjusted rounds</b> · {date(slice.start??undefined)} to {date(slice.end??undefined)} · {slice.tours.map(t=>t.toUpperCase()).join(" / ")||"No covered tours"}</p><div className="pd-statstrip"><span><b>{summary.n}</b> adjusted rounds</span><span><b>{signed(summary.p10)}</b> 10th percentile</span><span><b>{signed(summary.median)}</b> Median</span><span><b>{signed(summary.p90)}</b> 90th percentile</span><span><b>{fraction(summary.plus3)}</b> ≥ +3 SG</span><span><b>{fraction(summary.minus3)}</b> ≤ −3 SG</span></div>
    {!values.length?<p className="pd-empty">No source-adjusted rounds match these filters. Field-relative feeder results remain available in the event table.</p>:<svg className="pd-hist" viewBox="0 0 780 190" role="img" aria-label={`Empirical adjusted round SG histogram, ${summary.n} rounds. ${all?"All played rounds":"First and second rounds"}. Frequency is not a forecast.`}>{bins.map((b,i)=>{const h=b.count/max*130;return <g key={i}><rect x={48+i*43} y={146-h} width="36" height={h} rx="2" fill={b.x<0?"var(--chart-1)":"var(--chart-2)"} fillOpacity=".75"><title>{i===0?"Below -7":i===bins.length-1?"+7 and above":`${b.x} to ${b.x+1}`} SG: {b.count} rounds ({fraction(b.share)})</title></rect>{i%2===0&&<text x={48+i*43} y="170" fill="var(--muted)" fontSize="11">{b.x>0?"+":""}{b.x}</text>}</g>;})}<text x="740" y="187" textAnchor="end" fill="var(--muted)" fontSize="10">{center?"SG from own median →":"Adjusted SG / round →"}</text></svg>}
    <p className="pd-muted">Historical frequencies among this player’s played rounds matching the event filters. {all?"All rounds include cut-survivor selection.":"R1/R2 avoids selecting only rounds played after making the cut."} End bars include the tails. {summary.n>0&&summary.n<20?"Small sample: treat the shape as exploratory. ":""}Rounds are clustered within events. Schedule, weather and changing ability remain in the spread; this is not intrinsic variance, a forecast probability, a tournament ceiling or a cut estimate. {center?"Chart zero is this player’s own median; the numeric quantiles and ±3 frequencies above remain on absolute adjusted SG.":""}</p><details className="pd-method"><summary>Shot-level outcome distributions</summary><p>Shot SG uses a different raw expected-strokes baseline from the adjusted round histogram. Physical shots only; starting-state opportunity mix remains.</p>{deep.shots?.distributions?.map(d=><div className="pd-shot-dist" key={d.key}><b>{d.label}</b><span>{d.n_shots.toLocaleString()} shots</span><div className="pd-mini-bars">{d.counts.map((n,i)=><i key={i} style={{height:`${Math.max(2,n/Math.max(1,...d.counts)*46)}px`}} title={`${i===0?"Below -1":i===d.counts.length-1?"+1 and above":`${d.edges[i]} to ${d.edges[i+1]}`} SG: ${n} shots`}/>)}</div><small>These shot samples cover the fixed published detail window and do not respond to event filters above.</small></div>)}{!deep.shots?.distributions?.length&&<p>No supported shot distribution was published.</p>}</details>
  </>;
}

function Comparison({profile,filters,all,center,primary,primaryName}:{profile:PlayerProfile;filters:EventFilters;all:boolean;center:boolean;primary:DeepProfile;primaryName:string}){
  if(!profile.deep_key)return <p className="pd-muted">{profile.identity.name}: deep history unavailable.</p>;
  return <LoadedComparison key={profile.deep_key} profile={profile} filters={filters} all={all} center={center} primary={primary} primaryName={primaryName}/>;
}
function LoadedComparison({profile,filters,all,center,primary,primaryName}:{profile:PlayerProfile;filters:EventFilters;all:boolean;center:boolean;primary:DeepProfile;primaryName:string}){
  const load=useDashboardData<unknown>(profileKey(profile.deep_key!));
  const [matched,setMatched]=useState(false);
  const deep=parseDeep(load.data,String(playerId(profile.identity)));
  if(load.loading)return <p className="pd-muted">Loading {profile.identity.name} comparison…</p>;
  if(!deep || load.error)return <p className="pd-muted">{profile.identity.name}: matching comparison history unavailable.</p>;
  if(deep.as_of!==primary.as_of)return <p className="pd-muted">{profile.identity.name}: comparison withheld because publication dates differ.</p>;
  const peerAll=filterEvents(deep.history?.events??[],filters),ownAll=filterEvents(primary.history?.events??[],filters),commonSlices=commonEventSlices(ownAll,peerAll,all);
  const peerEvents=matched?commonSlices.b:peerAll,primaryEvents=matched?commonSlices.a:ownAll;
  const peer=roundValues(peerEvents,all),own=roundValues(primaryEvents,all),s=distributionSummary(peer),slice=evidenceSlice(peerEvents,all);
  const common=commonSlices.n_common;
  const a=histogram(centeredValues(own,center)),b=histogram(centeredValues(peer,center)),max=Math.max(.01,...a.map(v=>v.share),...b.map(v=>v.share));
  const line=(bins:typeof a)=>bins.map((v,i)=>`${58+i*43},${134-v.share/max*110}`).join(" ");
  return <div className="pd-compare-block"><div className="pd-compare"><a href={`/players?player=${encodeURIComponent(String(playerId(profile.identity)))}`}>{profile.identity.name}</a><span>{slice.n_events} events · {s.n} rounds</span><span>Median <b>{signed(s.median)}</b></span><span>P10 <b>{signed(s.p10)}</b></span><span>P90 <b>{signed(s.p90)}</b></span></div><p className="pd-muted">{date(slice.start??undefined)} to {date(slice.end??undefined)} · {slice.tours.map(t=>t.toUpperCase()).join(" / ")||"No covered tours"} · {common} common events with adjusted coverage; {matched?"overlays restricted to these common events":"distributions use each player’s own event set"}.</p><label className="pd-check"><input type="checkbox" checked={matched} onChange={e=>setMatched(e.target.checked)}/>Only common events · course rounds and weather can still differ</label>{peer.length&&own.length?<><svg className="pd-overlay" viewBox="0 0 780 172" role="img" aria-label={`${primaryName} and ${profile.identity.name}: empirical normalized histogram overlay, ${center?"centered on each player's own median":"absolute adjusted round SG"}. Descriptive observed rounds; not forecast variance.`}><line x1="36" x2="742" y1="134" y2="134" stroke="var(--line)"/><polyline points={line(a)} fill="none" stroke="var(--chart-2)" strokeWidth="2.5"/><polyline points={line(b)} fill="none" stroke="var(--chart-1)" strokeWidth="2.5" strokeDasharray="5 3"/>{[-8,-4,0,4,7].map(v=><text key={v} x={58+(v+8)*43} y="155" textAnchor="middle" fontSize="11" fill="var(--muted)">{v>0?"+":""}{v}</text>)}</svg><div className="pd-legend"><span><i style={{background:"var(--chart-2)"}}/>{primaryName} · {own.length} rounds</span><span><i style={{background:"var(--chart-1)"}}/>{profile.identity.name} · {peer.length} rounds · dashed</span></div></>:<p className="pd-empty">Both players need covered adjusted rounds for an overlay.</p>}</div>;
}

export function ProfileDeepDive({deep,profile,comparisons=[]}:{deep:DeepProfile|null;profile:PlayerProfile;comparisons?:PlayerProfile[]}){
  const [filters,setFilters]=useState<EventFilters>({...DEFAULT_FILTERS});
  const [metric,setMetric]=useState<EventMetric>("sg_total"),[order,setOrder]=useState<"date"|"asc"|"desc">("date");
  const [page,setPage]=useState(0),[expanded,setExpanded]=useState<string[]>([]),[all,setAll]=useState(false),[center,setCenter]=useState(false);
  const events=useMemo(()=>deep?.history?.events??[],[deep]);
  const activeFilters=useMemo(()=>({...filters,asOf:deep?.as_of}),[filters,deep?.as_of]);
  const filtered=useMemo(()=>filterEvents(events,activeFilters),[events,activeFilters]);
  const sorted=useMemo(()=>sortEvents(filtered,order==="date"?"date":metric,order==="asc"?"asc":"desc"),[filtered,metric,order]);
  if(!deep)return <Panel title="Deep history"><p className="pd-empty">No matching deep profile has been published for {profile.identity.name}. Missing history is not zero performance.</p></Panel>;
  const patch=(change:Partial<EventFilters>)=>{setFilters(f=>({...f,...change}));setPage(0);};
  const pages=Math.max(1,Math.ceil(sorted.length/15)),current=Math.min(page,pages-1),visible=sorted.slice(current*15,(current+1)*15);
  const seasons=[...new Set(events.map(e=>e.year))].sort((a,b)=>b-a),tours=[...new Set(events.map(e=>e.tour))].sort();
  const summary=distributionSummary(roundValues(filtered)),metricLabel=EVENT_METRICS.find(m=>m.key===metric)!;
  return <div className="pd-deep"><Panel title="A golfer in context" eyebrow="Observed performance · separate from model skill"><p className="pd-tldr"><b>{filtered.length} events</b> in view · <b>{summary.n} source-adjusted R1/R2 rounds</b> · median <b>{signed(summary.median)} SG</b>. Explore the conditions below before judging the spread.</p><PerformanceTrend deep={deep} anchor={profile.pga_benchmark_reference?.adjusted_sg_mean}/><details className="pd-method"><summary>Optional legacy model history</summary><p>The main chart follows actual adjusted performance. This separate legacy estimate blends and smooths multiple inputs; it is useful for comparing what the old estimator inferred, rather than reading recent results.</p><BaselineChart deep={deep}/></details></Panel>
    <Panel title="Event record" eyebrow="Filter the history, then inspect the rounds"><div className="pd-filters">
      <label>History window<select value={filters.window??"recent2y"} onChange={e=>patch({window:e.target.value as "recent2y"|"all"})}><option value="recent2y">Past 2 years at profile date</option><option value="all">All available history</option></select></label><label>Season<select value={filters.season} onChange={e=>patch({season:e.target.value,window:"all"})}><option value="">All seasons</option>{seasons.map(y=><option key={y}>{y}</option>)}</select></label>
      <label>Tour<select value={filters.tour} onChange={e=>patch({tour:e.target.value})}><option value="">All tours</option>{tours.map(t=><option key={t} value={t}>{t.toUpperCase()}</option>)}</select></label>
      <label>Opening-round field scoring<select value={filters.difficulty} onChange={e=>patch({difficulty:e.target.value})}><option value="">Any difficulty</option><option value="hard">Field &gt; +1 vs par</option><option value="moderate">Field −1 to +1</option><option value="easy">Field &lt; −1 vs par</option></select></label>
      <label>Opening-round source field offset<select value={filters.strength} onChange={e=>patch({strength:e.target.value})}><option value="">Any field</option><option value="strong">Source offset ≥ 0 SG</option><option value="weak">Source offset &lt; 0 SG</option></select></label>
      <label className="pd-search">Event or course<input type="search" value={filters.search} placeholder="Find a venue or event…" onChange={e=>patch({search:e.target.value})}/></label>
      <label className="pd-check"><input type="checkbox" checked={filters.major} onChange={e=>patch({major:e.target.checked})}/>Majors only</label>
      <button className="pd-reset" onClick={()=>{setFilters({...DEFAULT_FILTERS});setPage(0);}}>Reset filters</button>
    </div><div className="pd-context"><span>{filtered.length} of {events.length} published events · window anchored to {date(deep.as_of)}</span><span>Context bands use R1/R2 means, independent of weekend survival</span><span>Weather filter unavailable · historical units uncertified</span><span>Course-type filter unavailable · verified registry needed</span></div>
    <section className="pd-round-overview"><span className="eyebrow">Empirical outcomes · same event filters</span><h3>How the rounds spread out</h3><label className="pd-check"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Include rounds 3 and 4</label><label className="pd-check"><input type="checkbox" checked={center} onChange={e=>setCenter(e.target.checked)}/>Center charts on each player’s median</label><RoundDistribution deep={deep} events={filtered} all={all} center={center}/>{comparisons.length>0&&<div className="pd-comparisons"><h3>Compare the same historical slice</h3>{comparisons.slice(0,2).map(p=><Comparison key={playerId(p.identity)} profile={p} filters={activeFilters} all={all} center={center} primary={deep} primaryName={profile.identity.name}/>)}<p className="pd-muted">Overlaid bin shares sum to 100% for each player; identical axes and SG units. Same filters select different event sets. Median-centered spread removes each player’s observed median, not course/weather effects or changing ability.</p></div>}</section>
<div className="pd-table-tools"><label>Metric<select value={metric} onChange={e=>{setMetric(e.target.value as EventMetric);setPage(0);}}>{EVENT_METRICS.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label><label>Sort<select value={order} onChange={e=>{setOrder(e.target.value as typeof order);setPage(0);}}><option value="date">Most recent</option><option value="desc">Metric · highest first</option><option value="asc">Metric · lowest first</option></select></label></div>
    <div className="pd-scroll"><table className="pd-table pd-events"><caption>{metricLabel.label}, mean per played round. Adjusted totals and field-relative categories use distinct baselines. Expand an event to inspect its rounds.</caption><thead><tr><th>Event / course</th><th>Finish</th><th>Rounds</th><th>{metricLabel.label}<small>{metricLabel.unit}</small></th><th>Source field offset<small>R1/R2 mean · SG/round</small></th><th>Field scoring<small>R1/R2 mean vs par</small></th></tr></thead><tbody>{visible.map(e=><Fragment key={e.id}><tr><th scope="row"><button className="pd-expand" aria-expanded={expanded.includes(e.id)} onClick={()=>setExpanded(x=>x.includes(e.id)?x.filter(v=>v!==e.id):[...x,e.id])}><span aria-hidden="true">{expanded.includes(e.id)?"−":"+"}</span>{e.name}</button><small>{date(e.date)} · {e.tour.toUpperCase()} {e.major?"· Major":""}</small><small>{e.course||"Course unavailable"}</small></th><td>{e.finish||"—"}</td><td>{e.rounds??e.round_data?.length??0}</td><td className={metric!=="score_to_par"&&finite(eventMetricValue(e,metric))&&eventMetricValue(e,metric)!>0?"pd-positive":""}>{signed(eventMetricValue(e,metric))}{e.sg_basis!=="source_adjusted"&&metric==="sg_total"?<small>Adjusted total unavailable</small>:null}</td><td>{signed(openingContext(e,"field_strength"))}</td><td>{signed(openingContext(e,"difficulty"))}</td></tr>{expanded.includes(e.id)&&<tr className="pd-rounds"><td colSpan={6}><table className="pd-table"><caption>{e.name} · source-adjusted total; categories remain field-relative</caption><thead><tr><th>Round</th><th>Date</th><th>Score</th><th>Total SG</th><th>OTT</th><th>APP</th><th>ARG</th><th>PUTT</th></tr></thead><tbody>{(e.round_data??[]).map((r,i)=><tr key={i}><th>R{r.round??r.round_num??"?"}</th><td>{date(r.date)}</td><td>{r.score??"—"}</td><td>{signed(r.sg_basis==="source_adjusted"?r.sg_total:null)}</td><td>{signed(r.sg_ott)}</td><td>{signed(r.sg_app)}</td><td>{signed(r.sg_arg)}</td><td>{signed(r.sg_putt)}</td></tr>)}</tbody></table></td></tr>}</Fragment>)}</tbody></table></div>
    {!visible.length&&<p className="pd-empty">No events match these filters. Reset the filters to see this player’s published history.</p>}
    <div className="pd-pagination"><button disabled={current===0} onClick={()=>setPage(current-1)}>← Previous</button><span>Page {current+1} / {pages}</span><button disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next →</button></div>
    <details className="pd-method"><summary>Coverage and filter definitions</summary><p>Field scoring is the observed course-round field average score minus par, with at least 20 source field records, averaged only over this player’s available R1/R2 rounds. Context filters exclude missing opening-round context and cannot depend on whether the player survived the cut. It contains weather and setup effects. The source field offset is likewise averaged over R1/R2; it is the published provider adjustment offset; zero is its source baseline, not the fixed PGA headline reference. Selecting a context filter excludes events with missing context.</p><p>Feeder events remain field-relative unless published adjusted totals are available. Dates may be imputed from completion in feeder publications. A missing number is shown as a dash. History is bounded by the published event/round limits.</p><p>Published history: {String(deep.history?.coverage?.displayed_rounds??"unknown")} displayed rounds of {String(deep.history?.coverage?.total_rounds??"unknown")} source rounds. Missing or uncovered rounds cannot contribute to the chart.</p></details>
    </Panel></div>;
}
