"use client";
import {Fragment,useState} from "react";
import {Panel} from "./components";
import {useDashboardData} from "./data";
import {playerId,profileKey,type PlayerProfile} from "./player-profile-rules";
import {EVENT_METRICS,GLOSS,dayText,unitText,finite,histogram,parseDeep,sortEvents,eventMetricValue,type DeepProfile,type EventMetric} from "./player-deep-rules";
import {adjustedValues,decodeReference,hasSituationFilters,playerBaselineFilters,matchedPgaEvents,sliceHistory,summaryWithMean,type ContextEvent,type ContextRound,type HistoryFilters} from "./player-history-filters";
const signed=(v:unknown)=>finite(v)?`${v>0?"+":""}${v.toFixed(2)}`:"—";
const date=(s:string|undefined)=>dayText(s,"");
export function HistoryHistogram({own,peer=[],baseline,peerLabel="PGA field",name,center=false}:{own:number[];peer?:number[];baseline?:number[];peerLabel?:string;name:string;center?:boolean}){
 const stats=summaryWithMean(own),ps=summaryWithMean(peer),bs=summaryWithMean(baseline??[]),offset=center?stats.median??0:0,poffset=center?ps.median??0:0,boffset=center?bs.median??0:0,a=histogram(own.map(v=>v-offset)),b=histogram(peer.map(v=>v-poffset)),c=histogram((baseline??[]).map(v=>v-boffset)),max=Math.min(1,Math.max(.05,...a.map(v=>v.share),...b.map(v=>v.share),...c.map(v=>v.share))*1.12);
 const x=(v:number)=>52+Math.max(0,Math.min(16,v+8))*43,y=(p:number)=>208-p/max*146;
 return <>{stats.n>0&&stats.n<20&&<p className="pd-shape-coverage"><b>Small sample · {stats.n} round{stats.n===1?"":"s"}.</b> Treat this as description, not a lasting trait.</p>}<div className="pd-distribution-head"><article><span title="Average strokes gained per round, on a fixed PGA scale (0 = the PGA average).">Average strokes gained / round</span><strong>{signed(stats.mean)}</strong><small>Across the selected rounds</small>{baseline&&<small>Baseline {signed(bs.mean)} · difference {signed(finite(stats.mean)&&finite(bs.mean)?stats.mean-bs.mean:null)}</small>}</article><article><span title="The middle round: half the rounds were better, half worse. Less swayed by one blow-up round than the average.">Median strokes gained / round</span><strong>{signed(stats.median)}</strong><small>Half the rounds above, half below</small>{baseline&&<small>Baseline {signed(bs.median)} · difference {signed(finite(stats.median)&&finite(bs.median)?stats.median-bs.median:null)}</small>}</article><div><b>{stats.n.toLocaleString()} player rounds</b><span title="Eight in ten rounds fall between these two numbers.">Typical range (middle 80% of rounds): {signed(stats.p10)} to {signed(stats.p90)}</span>{baseline&&<span>Player baseline: {bs.n.toLocaleString()} rounds</span>}{peer.length>0&&<span>{peerLabel}: {ps.n.toLocaleString()} rounds · average {signed(ps.mean)} · median {signed(ps.median)}</span>}</div></div>
 {!own.length&&<p className="pd-empty">No rounds with adjusted strokes gained match these filters. {bs.n?"The player baseline remains visible.":"Change the filters to see covered results."}</p>}
 {own.length>0||bs.n>0||peer.length>0?<><svg className="pd-hist pd-hist-large" viewBox="0 0 780 258" role="img" aria-label={`${name} round distribution with average ${signed(stats.mean)} and median ${signed(stats.median)}. ${baseline?`Player baseline: ${bs.n} rounds, average ${signed(bs.mean)}, median ${signed(bs.median)}.`:""} ${peer.length?`${peerLabel} overlay.`:""} Each group is shown as a share of its own rounds.`}>
 {[0,.25,.5,.75,1].map(p=><g key={p}><line x1="52" x2="740" y1={y(max*p)} y2={y(max*p)} stroke="var(--line)"/><text x="43" y={y(max*p)+4} textAnchor="end" fontSize="10" fill="var(--muted-strong)">{Math.round(max*p*100)}%</text></g>)}
 {a.map((v,i)=>{const groups=[{key:"own",bin:v,fill:"var(--chart-1)",op:.7,label:name},...(bs.n>0?[{key:"base",bin:c[i],fill:"var(--muted-strong)",op:.55,label:"Player baseline"}]:[]),...(peer.length>0?[{key:"peer",bin:b[i],fill:"var(--chart-3)",op:.6,label:peerLabel}]:[])],w=35/groups.length;return <g key={i}>{groups.map((g,k)=><rect key={g.key} x={x(v.x)+4+k*w} y={y(g.bin.share)} width={Math.max(2,w-1)} height={208-y(g.bin.share)} rx="2" fill={g.fill} fillOpacity={g.op}><title>{g.label} · {i===0?"below −7":i===15?"+7 and above":`${v.x} to ${v.x+1}`} strokes gained: {g.bin.count} rounds · {(g.bin.share*100).toFixed(1)}%</title></rect>)}{i%2===0&&<text x={x(v.x)} y="228" textAnchor="middle" fontSize="11" fill="var(--muted-strong)">{v.x>0?"+":""}{v.x}</text>}</g>;})}
 {finite(stats.mean)&&<g><line x1={x(stats.mean-offset)} x2={x(stats.mean-offset)} y1="52" y2="208" stroke="var(--chart-1)" strokeWidth="2.5"/><text x={x(stats.mean-offset)} y="16" textAnchor="middle" fill="var(--chart-1)" fontSize="12" fontWeight="600">Average {signed(stats.mean)}{Math.abs(stats.mean-offset)>8?" (off scale)":""}</text></g>}
 {finite(stats.median)&&<g><line x1={x(stats.median-offset)} x2={x(stats.median-offset)} y1="52" y2="208" stroke="var(--chart-2)" strokeWidth="2" strokeDasharray="3 3"/><text x={x(stats.median-offset)} y="36" textAnchor="middle" fill="var(--chart-2)" fontSize="12" fontWeight="600">Median {signed(stats.median)}{Math.abs(stats.median-offset)>8?" (off scale)":""}</text></g>}
 <text x="740" y="250" textAnchor="end" fill="var(--muted-strong)" fontSize="11">{center?"Strokes gained, measured from each group’s own median":"Strokes gained per round vs the PGA average"} →</text></svg>
 <div className="pd-legend"><span><i style={{background:"var(--chart-1)"}}/>{name} · selected rounds</span>{bs.n>0&&<span><i style={{background:"var(--muted-strong)"}}/>Player’s overall baseline</span>}{peer.length>0&&<span><i style={{background:"var(--chart-3)"}}/>{peerLabel}</span>}<span><i style={{background:"var(--chart-2)"}}/>Median line</span></div></>:null}
 </>;
}
function PgaHistogram({referenceKey,deep,selected,filters,own,baseline,anchor,name,center}:{referenceKey:string;deep:DeepProfile;selected:ContextEvent[];filters:HistoryFilters;own:number[];baseline?:number[];anchor:number|undefined|null;name:string;center:boolean}){
 const load=useDashboardData<unknown>(profileKey(referenceKey)),reference=decodeReference(load.data,deep.as_of,new Set(selected.map(e=>e.id))),matched=matchedPgaEvents(reference,selected,filters),values=adjustedValues(matched,anchor),n=new Set(matched.map(e=>e.id)).size,total=selected.length;
 return <><HistoryHistogram own={own} baseline={baseline} peer={values} name={name} center={center}/>{load.loading?<p role="status" className="pd-muted">Loading the PGA comparison…</p>:load.error?<p role="status" className="pd-muted">The PGA comparison could not be loaded.</p>:<p className="pd-muted"><b>PGA field comparison:</b> {values.length.toLocaleString()} rounds by PGA players from {n} of your {total} selected events, matched to the same rounds and starting positions. Feeder events have no PGA counterpart.</p>}</>;
}
function Peer({profile,primary,filters,anchor,name,center}:{profile:PlayerProfile;primary:ContextEvent[];filters:HistoryFilters;anchor:number|null|undefined;name:string;center:boolean}){
 const load=useDashboardData<unknown>(profileKey(profile.deep_key??"unavailable.json")),d=parseDeep(load.data,String(playerId(profile.identity))),[common,setCommon]=useState(false);
 if(load.loading)return <p className="pd-muted">Loading {profile.identity.name}…</p>;
 if(!d||d.as_of!==filters.asOf)return <p className="pd-muted">Comparison history is not available for this player.</p>;
 const selected=sliceHistory(d.history?.events??[],filters),ids=new Set(selected.map(e=>e.id)),commonIds=new Set(primary.filter(e=>ids.has(e.id)).map(e=>e.id)),a=common?primary.filter(e=>commonIds.has(e.id)):primary,b=common?selected.filter(e=>commonIds.has(e.id)):selected;
 return <div className="pd-compare-block"><h4>{name} vs {profile.identity.name}</h4><label className="pd-check"><input type="checkbox" checked={common} onChange={e=>setCommon(e.target.checked)}/>Only common events · {commonIds.size} available</label><HistoryHistogram own={adjustedValues(a,anchor)} peer={adjustedValues(b,anchor)} name={name} peerLabel={profile.identity.name} center={center}/><p className="pd-muted">Same filters for both players, using {common?"only events both played":"each player’s own schedule"}. These are past results, not forecasts.</p></div>;
}
export function PlayerHistoryExplorer({deep,profile,filters,comparisons=[],referenceKey}:{deep:DeepProfile;profile:PlayerProfile;filters:HistoryFilters;comparisons?:PlayerProfile[];referenceKey?:string}){
 const [metric,setMetric]=useState<EventMetric>("sg_total"),[order,setOrder]=useState<"date"|"asc"|"desc">("date"),[page,setPage]=useState(0),[expanded,setExpanded]=useState<string[]>([]),[overlay,setOverlay]=useState(true),[center,setCenter]=useState(false);
 const rc=(e:ContextEvent,k:string)=>e.round_data.some(r=>k==="score"?finite(r.score):k==="gap"?finite((r as ContextRound).strokes_behind_leader_before):k==="adj"?r.sg_basis==="source_adjusted"&&finite(r.sg_total)&&finite(anchor):finite((r as unknown as Record<string,unknown>)[k]));
 const active={...filters,asOf:deep.as_of},selected=sliceHistory(deep.history?.events??[],active),sorted=sortEvents(selected,order==="date"?"date":metric,order==="asc"?"asc":"desc"),pages=Math.max(1,Math.ceil(sorted.length/15)),current=Math.min(page,pages-1),visible=sorted.slice(current*15,current*15+15),anchor=profile.pga_benchmark_reference?.adjusted_sg_mean,own=adjustedValues(selected,anchor),baseline=hasSituationFilters(active)?adjustedValues(sliceHistory(deep.history?.events??[],playerBaselineFilters(active)),anchor):undefined,ml=EVENT_METRICS.find(m=>m.key===metric)!,hasFinish=visible.some(e=>e.finish);
 return <Panel title="Event record & round outcomes" eyebrow="Selected rounds · follows the filters above"><a className="pd-muted" href="#player-history-filters">Change filters ↑</a><div className="pd-heading"><div><h3>How the rounds spread out</h3><p className="pd-muted">{selected.length} events · {own.length} rounds · R{filters.rounds.join(" / R")||"none"} · {filters.contention==="all"?"any starting position":filters.contention==="near"?"within 2 shots of the lead before R3/R4":"more than 2 shots back before R3/R4"}</p></div><div><label className="pd-check"><input type="checkbox" checked={overlay} onChange={e=>setOverlay(e.target.checked)}/>Compare with the PGA field</label><label className="pd-check"><input type="checkbox" checked={center} onChange={e=>setCenter(e.target.checked)}/>Line up the medians (compare spread only)</label></div></div>
 {overlay&&referenceKey?<PgaHistogram referenceKey={referenceKey} deep={deep} selected={selected} filters={active} own={own} baseline={baseline} anchor={anchor} name={profile.identity.name} center={center}/>:<><HistoryHistogram own={own} baseline={baseline} name={profile.identity.name} center={center}/>{overlay&&<p className="pd-muted">No PGA comparison is published for this player list.</p>}</>}
 {baseline&&<p className="pd-muted"><b>Player’s overall baseline:</b> the same player, period and tour across all rounds and situations. The selected rounds are part of it, so differences describe the sample and do not prove a cause.</p>}
 <details className="pd-method"><summary>How this is calculated</summary><p>Strokes gained per round is measured against a fixed PGA average (0 = average), adjusted for field strength. The average and median cards always show the true values; lining up medians only moves the drawing. The end bars include everything beyond ±7. {filters.rounds.some(r=>r>=3)&&"Weekend rounds only include players who made the cut. "}Small samples are descriptive, and field quality, schedule and weather can explain differences. Each group is drawn as a share of its own rounds, so groups of different sizes are comparable.</p></details>
 {comparisons.map(p=><Peer key={playerId(p.identity)} profile={p} primary={selected} filters={active} anchor={anchor} name={profile.identity.name} center={center}/>)}
 <div className="pd-table-tools"><label>Show<select value={metric} onChange={e=>{setMetric(e.target.value as EventMetric);setPage(0);}}>{EVENT_METRICS.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label><label>Order<select value={order} onChange={e=>{setOrder(e.target.value as typeof order);setPage(0);}}><option value="date">Most recent</option><option value="desc">Highest first</option><option value="asc">Lowest first</option></select></label></div>
 <div className="pd-scroll"><table className="pd-table pd-events"><caption>{ml.label}, averaged over the selected rounds. Click an event to see each round.</caption><thead><tr><th>Event / course</th>{hasFinish&&<th title={GLOSS.finish}>Finish</th>}<th title="Which rounds of the event are included in the filters.">Rounds</th><th title={ml.help}>{ml.label}<small>{unitText(ml.unit)}</small></th></tr></thead><tbody>{visible.map(e=><Fragment key={e.id}><tr><th scope="row"><button className="pd-expand" aria-expanded={expanded.includes(e.id)} onClick={()=>setExpanded(s=>s.includes(e.id)?s.filter(v=>v!==e.id):[...s,e.id])}><span>{expanded.includes(e.id)?"−":"+"}</span>{e.name}</button><small>{date(e.date)} · {e.tour.toUpperCase()}{e.major?" · Major":""}</small>{e.course&&<small>{e.course}</small>}</th>{hasFinish&&<td>{e.finish??""}</td>}<td>{e.round_data.map(r=>`R${r.round??r.round_num}`).join(", ")}</td><td>{signed(metric==="sg_total"?(finite(eventMetricValue(e,metric))&&finite(anchor)?eventMetricValue(e,metric)!-anchor:null):eventMetricValue(e,metric))}</td></tr>{expanded.includes(e.id)&&<tr className="pd-rounds"><td colSpan={hasFinish?4:3}><table className="pd-table"><caption>{e.name} · selected rounds</caption><thead><tr><th>Round</th><th>Date</th>{rc(e,"score")&&<th>Score</th>}{rc(e,"gap")&&<th title={GLOSS.startGap}>Shots behind lead</th>}{rc(e,"adj")&&<th title={GLOSS.adjTotal}>Total strokes gained</th>}{rc(e,"sg_ott")&&<th title={GLOSS.sgOtt}>Off the tee</th>}{rc(e,"sg_app")&&<th title={GLOSS.sgApp}>Approach</th>}{rc(e,"sg_arg")&&<th title={GLOSS.sgArg}>Around green</th>}{rc(e,"sg_putt")&&<th title={GLOSS.sgPutt}>Putting</th>}</tr></thead><tbody>{e.round_data.map((r,i)=><tr key={i}><th>R{r.round??r.round_num}</th><td>{date(r.date)}</td>{rc(e,"score")&&<td>{r.score??""}</td>}{rc(e,"gap")&&<td>{finite((r as ContextRound).strokes_behind_leader_before)?`${(r as ContextRound).strokes_behind_leader_before} back`:""}</td>}{rc(e,"adj")&&<td>{r.sg_basis==="source_adjusted"&&finite(r.sg_total)&&finite(anchor)?signed(r.sg_total-anchor):""}</td>}{rc(e,"sg_ott")&&<td>{finite(r.sg_ott)?signed(r.sg_ott):""}</td>}{rc(e,"sg_app")&&<td>{finite(r.sg_app)?signed(r.sg_app):""}</td>}{rc(e,"sg_arg")&&<td>{finite(r.sg_arg)?signed(r.sg_arg):""}</td>}{rc(e,"sg_putt")&&<td>{finite(r.sg_putt)?signed(r.sg_putt):""}</td>}</tr>)}</tbody></table></td></tr>}</Fragment>)}</tbody></table></div>
 {!visible.length&&<p className="pd-empty">No events match these filters. Reset the filters or pick another round.</p>}
 <div className="pd-pagination"><button disabled={current===0} onClick={()=>setPage(current-1)}>← Previous</button><span>Page {current+1} / {pages}</span><button disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next →</button></div>
 <details className="pd-method"><summary>About this data</summary><p>Positions before rounds 3 and 4 are rebuilt from completed earlier rounds, so they are close to, but not certified as, official leaderboards. Events without adjusted totals (mostly feeder tours) still appear in the table but are left out of the distribution chart. Weather and course-type filters are not offered until we have verified historical data.</p></details></Panel>;
}
