"use client";
import {useEffect,useId,useRef,useState} from "react";
import {Panel} from "./components";
import {HISTORY_DEFAULTS,sliceHistory,type ContextEvent,type HistoryFilters} from "./player-history-filters";
type Option={value:string;label:string};
function HistoryFacet({label,options,value,onChange}:{label:string;options:Option[];value:string;onChange:(v:string)=>void}){
 const id=useId(),[query,setQuery]=useState<string|null>(null),[open,setOpen]=useState(false),[active,setActive]=useState(-1),refs=useRef<Array<HTMLButtonElement|null>>([]);
 const selected=options.find(o=>o.value===value),text=query??selected?.label??"",matches=[...(!query?[{value:"",label:`All ${label.toLowerCase()}`}]:[]),...options.filter(o=>o.label.toLowerCase().includes((query??"").toLowerCase()))],shown=matches.slice(0,60);
 useEffect(()=>{if(open)refs.current[active]?.scrollIntoView({block:"nearest"});},[active,open]);
 const choose=(v:string)=>{onChange(v);setQuery(null);setOpen(false);setActive(0);};
 return <div className="pd-facet"><label htmlFor={id}>{label}</label><div className="pd-facet-input"><input id={id} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={`${id}-list`} aria-activedescendant={open&&shown[active]?`${id}-${active}`:undefined} placeholder={`All ${label.toLowerCase()} · type to find`} value={text} onFocus={()=>{setOpen(true);setActive(-1);}} onBlur={()=>setOpen(false)} onChange={e=>{setQuery(e.target.value);setOpen(true);setActive(0);if(value)onChange("");}} onKeyDown={e=>{if(e.key==="ArrowDown"){e.preventDefault();setOpen(true);setActive(i=>Math.min(shown.length-1,i+1));}if(e.key==="ArrowUp"){e.preventDefault();setActive(i=>Math.max(0,i-1));}if(e.key==="Enter"&&open&&shown[active]){e.preventDefault();choose(shown[active].value);}if(e.key==="Escape"){setOpen(false);setQuery(null);}}}/>{(value||query)&&<button type="button" aria-label={`Clear ${label.toLowerCase()}`} onClick={()=>choose("")}>×</button>}</div>{open&&<div className="pd-facet-menu" id={`${id}-list`} role="listbox" aria-label={label}>{shown.map((o,i)=><button ref={el=>{refs.current[i]=el;}} type="button" role="option" id={`${id}-${i}`} aria-selected={i===active} key={o.value} onPointerDown={e=>e.preventDefault()} onClick={()=>choose(o.value)}>{o.label}</button>)}{!shown.length&&<p>No matches. Clear the search to browse.</p>}{matches.length>60&&<p>{matches.length} matches · type more to narrow</p>}</div>}</div>;
}
export function PlayerHistoryFilters({events,asOf,filters,onChange}:{events:ContextEvent[];asOf:string;filters:HistoryFilters;onChange:(f:HistoryFilters)=>void}){
 const patch=(v:Partial<HistoryFilters>)=>onChange({...filters,...v}),selected=sliceHistory(events,{...filters,asOf}),n=selected.reduce((s,e)=>s+e.round_data.length,0),seasons=[...new Set(events.map(e=>e.year))].sort((a,b)=>b-a),tours=[...new Set(events.map(e=>e.tour))].sort(),courses=[...new Set(events.flatMap(e=>e.courses?.length?e.courses:e.course?[e.course]:[]))].sort();
 return <section id="player-history-filters"><Panel title="Explore a slice of their golf" eyebrow="One set of filters for the shapes, charts and event list"><div className="pd-filters pd-shared-filters">
 <label title="How far back to look.">History window<select value={filters.window} onChange={e=>patch({window:e.target.value as "recent2y"|"all"})}><option value="recent2y">Past 2 years</option><option value="all">All published history</option></select></label>
 <label>Season<select value={filters.season} onChange={e=>patch({season:e.target.value,window:"all"})}><option value="">All seasons</option>{seasons.map(y=><option key={y}>{y}</option>)}</select></label>
 <label>Tour<select value={filters.tour} onChange={e=>patch({tour:e.target.value})}><option value="">All tours</option>{tours.map(t=><option key={t} value={t}>{t.toUpperCase()}</option>)}</select></label>
 <label title="How low or high the whole field scored versus par in the opening rounds, which reflects course setup and weather.">Field scoring conditions<select value={filters.difficulty} onChange={e=>patch({difficulty:e.target.value})}><option value="">Any scoring difficulty</option><option value="hard">Hard · field &gt; +1 vs par</option><option value="moderate">Typical · field −1 to +1</option><option value="easy">Low scoring · field &lt; −1 vs par</option></select></label>
 <HistoryFacet label="Events" value={filters.event} options={events.map(e=>({value:e.id,label:`${e.name} · ${e.year} · ${e.tour.toUpperCase()}`}))} onChange={event=>patch({event})}/>
 <HistoryFacet label="Courses" value={filters.course} options={courses.map(c=>({value:c,label:c}))} onChange={course=>patch({course})}/>
 <label title="Where the player stood before the round started. Only applies to rounds 3 and 4.">Position before the round<select value={filters.contention} onChange={e=>{const contention=e.target.value as HistoryFilters["contention"];patch({contention,...(contention!=="all"?{rounds:filters.rounds.filter(r=>r>=3).length?filters.rounds.filter(r=>r>=3):[3,4]}:{})});}}><option value="all">Any position</option><option value="near">In contention · within 2 shots</option><option value="outside">Outside contention · over 2 back</option></select></label>
 <label className="pd-check"><input type="checkbox" checked={filters.major} onChange={e=>patch({major:e.target.checked})}/>Majors only</label>
 <fieldset className="pd-round-select"><legend>Rounds</legend>{[1,2,3,4].map(r=><label key={r}><input type="checkbox" checked={filters.rounds.includes(r)} disabled={filters.contention!=="all"&&r<3} onChange={e=>patch({rounds:e.target.checked?[...filters.rounds,r].sort():filters.rounds.filter(n=>n!==r)})}/>R{r}</label>)}</fieldset>
 <button className="pd-reset" onClick={()=>onChange(filters.defaultRounds?{...HISTORY_DEFAULTS,rounds:[...filters.defaultRounds],defaultRounds:[...filters.defaultRounds]}:{...HISTORY_DEFAULTS,rounds:[1,2,3,4]})}>Reset filters</button></div>
 <div className="pd-filter-status" role="status"><b>{selected.length} events · {n} played rounds</b><span>The shapes, charts and event list follow these filters. The headline rating and the long-term form chart do not.</span></div>
 <details className="pd-method"><summary>How the filters work</summary><p>{filters.defaultRounds?"Rounds 1 and 2 are included by default; tick rounds 3 and 4 to add the weekend.":"Rounds 1–4 are included by default."} Weekend rounds only include players who made the cut. “In contention” means tied for the lead or within two shots before round 3 or 4; rounds where the position is unknown are left out of those splits. A gap here does not prove a pressure effect.</p><p>Field scoring conditions use how the whole field scored versus par in rounds 1 and 2, so they include setup and weather; they are not a course-type label. Shot detail covers the last three years; older events can have strokes-gained totals without it. Weather and course-type filters will be added once we have verified history.</p></details></Panel></section>;
}
