import {etTime} from "./lib.ts";
export const finite=(v:unknown):v is number=>typeof v==="number" && Number.isFinite(v);
export type ShotMetric={key:string;label:string;value:number|null;unit:string;n_shots?:number;n_rounds?:number;n_events?:number;last_date?:string;status?:string;definition?:string;reference_z?:number|null;reference_percentile?:number|null;reference_n_players?:number;reference_id?:string;reference_as_of?:string;higher_is_better?:boolean};
export type RoundRow={round?:number;round_num?:number;date?:string;score?:number|null;par?:number|null;sg_total?:number|null;sg_total_field?:number|null;sg_ott?:number|null;sg_app?:number|null;sg_arg?:number|null;sg_putt?:number|null;field_strength?:number|null;difficulty?:number|null;wind?:number|null;temp?:number|null;sg_basis?:string};
export type HistoryEvent={id:string;tour:string;event_id?:number;year:number;name:string;date:string;finish?:string;course?:string;par?:number;rounds?:number;sg_total?:number|null;sg_total_field?:number|null;sg_ott?:number|null;sg_app?:number|null;sg_arg?:number|null;sg_putt?:number|null;score_to_par?:number|null;field_strength?:number|null;difficulty?:number|null;wind?:number|null;temp?:number|null;major?:boolean;sg_basis?:string;round_data:RoundRow[]};
export type Baseline={schema_version:string;label?:string;status?:string;value?:number|null;raw_value?:number|null;latest_date?:string;reference_id?:string;series:Array<{date:string;value:number;moving_average_90d?:number|null;moving_average_n?:number}>;limitations?:string[];source?:unknown};
export type DeepProfile={schema_version:string;profile_id:string;as_of:string;name?:string;history?:{events:HistoryEvent[];coverage?:Record<string,unknown>;source?:unknown;filters?:{weather?:{status?:string;units?:unknown}}};baseline?:Baseline|null;shots?:{metrics:ShotMetric[];coverage?:Record<string,unknown>;source?:unknown;reference_id?:string;distributions?:Array<{key:string;label:string;edges:number[];counts:number[];n_shots:number;note?:string}>}|null};
export function parseDeep(raw:unknown,id:string):DeepProfile|null{
  if(!raw || typeof raw!=="object")return null;
  const b=raw as {schema_version?:string;profiles?:Record<string,unknown>};
  if(b.schema_version==="player_deep.batch.v1")return parseDeep(b.profiles?.[id],id);
  const d=raw as DeepProfile;return d.schema_version==="player_deep.v1" && String(d.profile_id)===id ? d:null;
}
export type EventFilters={season:string;tour:string;major:boolean;difficulty:string;strength:string;search:string;window?:"recent2y"|"all";asOf?:string};
export function openingContext(event:HistoryEvent,key:"difficulty"|"field_strength"):number|null{const values=(event.round_data??[]).filter(r=>[1,2].includes(r.round??r.round_num??99)).map(r=>r[key]).filter(finite);return values.length?values.reduce((s,v)=>s+v,0)/values.length:null;}
export function filterEvents(events:HistoryEvent[],f:EventFilters):HistoryEvent[]{let start=-Infinity,end=Infinity;if(f.window==="recent2y"&&f.asOf&&Number.isFinite(Date.parse(f.asOf))){const d=new Date(f.asOf);end=d.getTime();d.setUTCHours(0,0,0,0);d.setUTCFullYear(d.getUTCFullYear()-2);start=d.getTime();}return events.filter(e=>{const difficulty=openingContext(e,"difficulty"),strength=openingContext(e,"field_strength");return(start===-Infinity||(Number.isFinite(Date.parse(e.date))&&Date.parse(e.date)>=start&&Date.parse(e.date)<=end))&&(!f.season || String(e.year)===f.season)&&(!f.tour || e.tour===f.tour)&&(!f.major || e.major===true)&&(!f.difficulty || (finite(difficulty) && (f.difficulty==="hard" ? difficulty>1:f.difficulty==="easy" ? difficulty< -1:Math.abs(difficulty)<=1)))&&(!f.strength || (finite(strength) && (f.strength==="strong" ? strength>=0:strength<0)))&&(!f.search || `${e.name} ${e.course ?? ""}`.toLowerCase().includes(f.search.toLowerCase()));});}
export function quantile(values:number[],p:number):number|null{if(!values.length)return null;const s=[...values].sort((a,b)=>a-b),x=(s.length-1)*p,i=Math.floor(x);return s[i]+(s[Math.min(i+1,s.length-1)]-s[i])*(x-i);}
export function roundValues(events:HistoryEvent[],all=false):number[]{return events.flatMap(e=>(e.round_data??[]).filter(r=>all || [1,2].includes(r.round ?? r.round_num ?? 99)).filter(r=>r.sg_basis==="source_adjusted").map(r=>r.sg_total)).filter(finite);}
export function histogram(values:number[],low=-8,high=8,step=1){const counts=Array.from({length:Math.ceil((high-low)/step)},(_,i)=>({x:low+i*step,count:0,share:0}));for(const v of values){const i=Math.max(0,Math.min(counts.length-1,Math.floor((v-low)/step)));counts[i].count++;}for(const b of counts)b.share=values.length?b.count/values.length:0;return counts;}
export function humanCheckpoint(stamp:string|null|undefined,kind?:string):string{if(!stamp || !Number.isFinite(Date.parse(stamp)))return "Saved time unavailable";return `${kind==="live" ? "Live update" : "Pre-event model"} · ${new Date(stamp).toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/New_York"})} ET`;}
export const DEFAULT_FILTERS:EventFilters={season:"",tour:"",major:false,difficulty:"",strength:"",search:"",window:"recent2y"};
export const EVENT_METRICS=[{key:"sg_total",label:"Total strokes gained",unit:"SG/round",help:"Strokes gained per round against a fixed PGA average, adjusted for the strength of each field."},{key:"sg_total_field",label:"Total vs the field",unit:"field SG/round",help:"Strokes gained per round compared with the other players in that week's field."},{key:"sg_ott",label:"Off the tee",unit:"field SG/round",help:"Strokes gained per round on tee shots, compared with that week's field."},{key:"sg_app",label:"Approach",unit:"field SG/round",help:"Strokes gained per round on approach shots, compared with that week's field."},{key:"sg_arg",label:"Around green",unit:"field SG/round",help:"Strokes gained per round on chips, pitches and bunker shots, compared with that week's field."},{key:"sg_putt",label:"Putting",unit:"field SG/round",help:"Strokes gained per round on the greens, compared with that week's field."},{key:"score_to_par",label:"Score vs par",unit:"strokes/round",help:"Average strokes over or under par per round."}] as const;
export type EventMetric=typeof EVENT_METRICS[number]["key"];
export function eventMetricValue(event:HistoryEvent,metric:EventMetric):number|null{if(metric==="sg_total"&&event.sg_basis!=="source_adjusted")return null;return finite(event[metric])?event[metric]:null;}
export function sortEvents(events:HistoryEvent[],metric:EventMetric|"date",direction:"asc"|"desc"):HistoryEvent[]{return [...events].sort((a,b)=>{if(metric==="date")return (direction==="desc" ? -1:1)*a.date.localeCompare(b.date);const av=eventMetricValue(a,metric),bv=eventMetricValue(b,metric);if(!finite(av))return finite(bv)?1:0;if(!finite(bv))return -1;return (direction==="desc" ? -1:1)*(av-bv)||b.date.localeCompare(a.date);});}
export function distributionSummary(values:number[]){const valid=values.filter(finite);return {n:valid.length,p10:quantile(valid,.1),median:quantile(valid,.5),p90:quantile(valid,.9),plus3:valid.length?valid.filter(v=>v>=3).length/valid.length:null,minus3:valid.length?valid.filter(v=>v<=-3).length/valid.length:null};}
export function metricValue(m:ShotMetric|undefined):number|null{return m?.status==="available"&&finite(m.value)?m.value:null;}
export function shapeRadius(m:ShotMetric|undefined):number|null{if(metricValue(m)===null || !finite(m?.reference_z))return null;return .5+Math.max(-2.5,Math.min(2.5,m.reference_z))/5;}
export function shapePoints(metrics:ShotMetric[],keys:string[]){const rs=keys.map(k=>shapeRadius(metrics.find(m=>m.key===k)));return {complete:rs.every(finite),radii:rs};}
export function formatMetric(value:unknown,unit:string){if(!finite(value))return "—";if(unit==="fraction")return `${(value*100).toFixed(1)}%`;if(unit==="strokes/shot" || unit==="SG/round" || unit==="field SG/round")return `${value>0?"+":""}${value.toFixed(2)}`;return value.toFixed(1);}
export function evidenceSlice(events:HistoryEvent[],all=false){const es=events.filter(e=>roundValues([e],all).length>0),dates=es.flatMap(e=>(e.round_data??[]).filter(r=>r.sg_basis==="source_adjusted"&&finite(r.sg_total)&&(all||[1,2].includes(r.round??r.round_num??99))).map(r=>r.date??e.date)).filter(v=>Number.isFinite(Date.parse(v))).sort();return {n_events:es.length,start:dates[0]??null,end:dates.at(-1)??null,seasons:[...new Set(es.map(e=>e.year))].sort(),tours:[...new Set(es.map(e=>e.tour))].sort()};}
export function centeredValues(values:number[],center:boolean){const median=quantile(values,.5);return center&&median!==null?values.map(v=>v-median):values;}
export function exploratoryStandouts(metrics:ShotMetric[],keys:string[]){return metrics.filter(m=>keys.includes(m.key)&&m.status==="available"&&(m.n_shots??0)>=100&&(m.n_rounds??0)>=10&&finite(m.reference_z)&&m.reference_z>.3).sort((a,b)=>b.reference_z!-a.reference_z!).slice(0,2);}
export function commonEventSlices(a:HistoryEvent[],b:HistoryEvent[],all=false){const aid=new Set(a.filter(e=>roundValues([e],all).length).map(e=>e.id)),bid=new Set(b.filter(e=>roundValues([e],all).length).map(e=>e.id));const common=new Set([...aid].filter(id=>bid.has(id)));return {a:a.filter(e=>common.has(e.id)),b:b.filter(e=>common.has(e.id)),n_common:common.size};}

/** Plain-English unit text for the table sub-labels. */
export function unitText(unit:string):string{return unit==="SG/round"?"strokes gained per round":unit==="field SG/round"?"strokes gained per round vs field":unit==="strokes/round"?"strokes per round":unit==="strokes/shot"?"strokes gained per shot":unit==="fraction"?"rate":unit;}
/** Hover definitions for jargon labels used across the player deep dive. */
export const GLOSS={
  sd:"How many standard deviations above (+) or below (−) the PGA average this is. About 1 is clearly good and 2 is elite; 0 is average.",
  sgOtt:"Strokes gained off the tee: how many shots per round the player gains or loses on tee shots compared with the benchmark.",
  sgApp:"Strokes gained on approach shots into the green, per round.",
  sgArg:"Strokes gained around the green (chips, pitches, bunker shots), per round.",
  sgPutt:"Strokes gained putting, per round.",
  adjTotal:"Total strokes gained per round on a fixed PGA scale, adjusted for the strength of the field that week.",
  percentile:"Where this player ranks among PGA players with enough shots. 90th means better than 90% of them.",
  startGap:"How many shots behind the leader the player was before starting the round.",
  finish:"Final finishing position for the whole event, not just the selected rounds.",
} as const;
/** Calendar dates (event and round days) read as plain dates; real timestamps read in US Eastern time. */
export function dayText(v:string|null|undefined,fallback="Not available"):string{
  if(!v)return fallback;
  if(/^\d{4}-\d{2}-\d{2}$/.test(v)){const d=new Date(`${v}T00:00:00Z`);return Number.isNaN(d.getTime())?fallback:d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"});}
  return etTime(v,fallback);
}
