"use client";
import {Fragment,useState} from "react";
import {Panel} from "./components";
import {useDashboardData} from "./data";
import {playerId,profileKey,type PlayerProfile} from "./player-profile-rules";
import {EVENT_METRICS,finite,histogram,parseDeep,sortEvents,eventMetricValue,type DeepProfile,type EventMetric} from "./player-deep-rules";
import {adjustedValues,decodeReference,matchedPgaEvents,sliceHistory,summaryWithMean,type ContextEvent,type ContextRound,type HistoryFilters} from "./player-history-filters";
const signed=(v:unknown)=>finite(v)?`${v>0?"+":""}${v.toFixed(2)}`:"—";
const date=(s:string|undefined)=>s&&Number.isFinite(Date.parse(s))?new Date(s).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}):"—";
export function HistoryHistogram({own,peer=[],peerLabel="PGA field",name,center=false}:{own:number[];peer?:number[];peerLabel?:string;name:string;center?:boolean}){
 const stats=summaryWithMean(own),ps=summaryWithMean(peer),offset=center?stats.median??0:0,poffset=center?ps.median??0:0,a=histogram(own.map(v=>v-offset)),b=histogram(peer.map(v=>v-poffset)),max=Math.min(1,Math.max(.05,...a.map(v=>v.share),...b.map(v=>v.share))*1.12);
 const x=(v:number)=>52+Math.max(0,Math.min(16,v+8))*43,y=(p:number)=>208-p/max*146;
 const line=b.map(v=>`${x(v.x+.5)},${y(v.share)}`).join(" ");
 return <>{stats.n>0&&stats.n<20&&<p className="pd-shape-coverage"><b>Small sample · {stats.n} round{stats.n===1?"":"s"}.</b> Performance in this slice is descriptive; a small sample cannot establish a lasting trait.</p>}<div className="pd-distribution-head"><article><span>Mean SG / round</span><strong>{signed(stats.mean)}</strong><small>Average performance in this slice</small></article><article><span>Median SG / round</span><strong>{signed(stats.median)}</strong><small>Half the rounds above, half below</small></article><div><b>{stats.n.toLocaleString()} player rounds</b><span>Middle 80%: {signed(stats.p10)} to {signed(stats.p90)}</span>{peer.length>0&&<span>{peerLabel}: {ps.n.toLocaleString()} rounds · mean {signed(ps.mean)} · median {signed(ps.median)}</span>}</div></div>
 {!own.length?<p className="pd-empty">No source-adjusted rounds match this slice. Change the filters to see covered results.</p>:<><svg className="pd-hist pd-hist-large" viewBox="0 0 780 258" role="img" aria-label={`${name} round distribution with mean ${signed(stats.mean)} and median ${signed(stats.median)}. ${peer.length?`${peerLabel} overlay, normalized separately to percentages.`:""}`}>
 {[0,.25,.5,.75,1].map(p=><g key={p}><line x1="52" x2="740" y1={y(max*p)} y2={y(max*p)} stroke="var(--line)"/><text x="43" y={y(max*p)+4} textAnchor="end" fontSize="10" fill="var(--muted-strong)">{Math.round(max*p*100)}%</text></g>)}
 {a.map((v,i)=><g key={i}><rect x={x(v.x)+4} y={y(v.share)} width="35" height={208-y(v.share)} rx="3" fill="var(--chart-1)" fillOpacity=".55"><title>{i===0?"Below −7":i===15?"+7 and above":`${v.x} to ${v.x+1}`} SG: {v.count} rounds · {(v.share*100).toFixed(1)}%</title></rect>{i%2===0&&<text x={x(v.x)} y="228" textAnchor="middle" fontSize="11" fill="var(--muted-strong)">{v.x>0?"+":""}{v.x}</text>}</g>)}
 {peer.length>0&&<polyline points={line} fill="none" stroke="var(--chart-3)" strokeWidth="3" strokeDasharray="6 4"/>}
 {finite(stats.mean)&&<g><line x1={x(stats.mean-offset)} x2={x(stats.mean-offset)} y1="52" y2="208" stroke="var(--chart-1)" strokeWidth="2.5"/><text x={x(stats.mean-offset)} y="16" textAnchor="middle" fill="var(--chart-1)" fontSize="12" fontWeight="600">Mean {signed(stats.mean)}{Math.abs(stats.mean-offset)>8?" (off scale)":""}</text></g>}
 {finite(stats.median)&&<g><line x1={x(stats.median-offset)} x2={x(stats.median-offset)} y1="52" y2="208" stroke="var(--chart-2)" strokeWidth="2" strokeDasharray="3 3"/><text x={x(stats.median-offset)} y="36" textAnchor="middle" fill="var(--chart-2)" fontSize="12" fontWeight="600">Median {signed(stats.median)}{Math.abs(stats.median-offset)>8?" (off scale)":""}</text></g>}
 <text x="740" y="250" textAnchor="end" fill="var(--muted-strong)" fontSize="11">{center?"SG from each population’s own median":"Adjusted SG / round vs fixed PGA reference"} →</text></svg>
 <div className="pd-legend"><span><i style={{background:"var(--chart-1)"}}/>{name} · bars</span><span><i style={{background:"var(--chart-2)"}}/>Player median · dotted</span>{peer.length>0&&<span><i style={{background:"var(--chart-3)"}}/>{peerLabel} · dashed</span>}</div></>}
 </>;
}
function PgaHistogram({referenceKey,deep,selected,filters,own,anchor,name,center}:{referenceKey:string;deep:DeepProfile;selected:ContextEvent[];filters:HistoryFilters;own:number[];anchor:number|undefined|null;name:string;center:boolean}){
 const load=useDashboardData<unknown>(profileKey(referenceKey)),reference=decodeReference(load.data,deep.as_of,new Set(selected.map(e=>e.id))),matched=matchedPgaEvents(reference,selected,filters),values=adjustedValues(matched,anchor),n=new Set(matched.map(e=>e.id)).size,total=selected.length;
 return <><HistoryHistogram own={own} peer={values} name={name} center={center}/>{load.loading?<p role="status" className="pd-muted">Loading the published PGA reference sample…</p>:load.error?<p role="status" className="pd-muted">PGA overlay unavailable: a matching reference publication could not be loaded.</p>:<p className="pd-muted"><b>PGA field overlay:</b> {values.length.toLocaleString()} source-adjusted PGA player rounds from {n} of your {total} selected events, using the same round and contention selection. Each round has equal weight. Feeder events have no PGA-field counterpart. Both distributions sum to 100%; this is the field’s spread, not a distribution of average-player ability.</p>}</>;
}
function Peer({profile,primary,filters,anchor,name,center}:{profile:PlayerProfile;primary:ContextEvent[];filters:HistoryFilters;anchor:number|null|undefined;name:string;center:boolean}){
 const load=useDashboardData<unknown>(profileKey(profile.deep_key??"unavailable.json")),d=parseDeep(load.data,String(playerId(profile.identity))),[common,setCommon]=useState(false);
 if(load.loading)return <p className="pd-muted">Loading {profile.identity.name}…</p>;
 if(!d||d.as_of!==filters.asOf)return <p className="pd-muted">Comparison history unavailable.</p>;
 const selected=sliceHistory(d.history?.events??[],filters),ids=new Set(selected.map(e=>e.id)),commonIds=new Set(primary.filter(e=>ids.has(e.id)).map(e=>e.id)),a=common?primary.filter(e=>commonIds.has(e.id)):primary,b=common?selected.filter(e=>commonIds.has(e.id)):selected;
 return <div className="pd-compare-block"><h4>{name} vs {profile.identity.name}</h4><label className="pd-check"><input type="checkbox" checked={common} onChange={e=>setCommon(e.target.checked)}/>Only common events · {commonIds.size} available</label><HistoryHistogram own={adjustedValues(a,anchor)} peer={adjustedValues(b,anchor)} name={name} peerLabel={profile.identity.name} center={center}/><p className="pd-muted">Identical filters; {common?"common events only":"each player’s own schedule"}. Played rounds can still differ. Observed outcomes are not forecast probabilities.</p></div>;
}
export function PlayerHistoryExplorer({deep,profile,filters,comparisons=[],referenceKey}:{deep:DeepProfile;profile:PlayerProfile;filters:HistoryFilters;comparisons?:PlayerProfile[];referenceKey?:string}){
 const [metric,setMetric]=useState<EventMetric>("sg_total"),[order,setOrder]=useState<"date"|"asc"|"desc">("date"),[page,setPage]=useState(0),[expanded,setExpanded]=useState<string[]>([]),[overlay,setOverlay]=useState(true),[center,setCenter]=useState(false);
 const active={...filters,asOf:deep.as_of},selected=sliceHistory(deep.history?.events??[],active),sorted=sortEvents(selected,order==="date"?"date":metric,order==="asc"?"asc":"desc"),pages=Math.max(1,Math.ceil(sorted.length/15)),current=Math.min(page,pages-1),visible=sorted.slice(current*15,current*15+15),anchor=profile.pga_benchmark_reference?.adjusted_sg_mean,own=adjustedValues(selected,anchor),ml=EVENT_METRICS.find(m=>m.key===metric)!;
 return <Panel title="Event record & round outcomes" eyebrow="Selected rounds · shared history filters"><a className="pd-muted" href="#player-history-filters">Change history filters ↑</a><div className="pd-heading"><div><h3>How the rounds spread out</h3><p className="pd-muted">{selected.length} events · {own.length} adjusted rounds · R{filters.rounds.join(" / R")||"none"} · {filters.contention==="all"?"any starting position":filters.contention==="near"?"within 2 before R3/R4":"over 2 back before R3/R4"}</p></div><div><label className="pd-check"><input type="checkbox" checked={overlay} onChange={e=>setOverlay(e.target.checked)}/>Overlay matching PGA field</label><label className="pd-check"><input type="checkbox" checked={center} onChange={e=>setCenter(e.target.checked)}/>Compare spread about each median</label></div></div>
 {overlay&&referenceKey?<PgaHistogram referenceKey={referenceKey} deep={deep} selected={selected} filters={active} own={own} anchor={anchor} name={profile.identity.name} center={center}/>:<><HistoryHistogram own={own} name={profile.identity.name} center={center}/>{overlay&&<p className="pd-muted">A matching PGA reference has not been published for this catalog.</p>}</>}
 <p className="pd-muted">Round SG uses the fixed 2025 PGA-start zero. Event table adjusted totals use the same fixed PGA zero; categories remain field-relative. Mean/median cards always show absolute adjusted SG; centering only shifts the drawing. End bins include tails. {filters.rounds.some(r=>r>=3)&&"Later rounds contain cut-survivor selection. "}Small contention samples are descriptive; field quality, schedule and weather can explain differences.</p>
 {comparisons.map(p=><Peer key={playerId(p.identity)} profile={p} primary={selected} filters={active} anchor={anchor} name={profile.identity.name} center={center}/>)}
 <div className="pd-table-tools"><label>Event metric<select value={metric} onChange={e=>{setMetric(e.target.value as EventMetric);setPage(0);}}>{EVENT_METRICS.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label><label>Order<select value={order} onChange={e=>{setOrder(e.target.value as typeof order);setPage(0);}}><option value="date">Most recent</option><option value="desc">Metric · highest first</option><option value="asc">Metric · lowest first</option></select></label></div>
 <div className="pd-scroll"><table className="pd-table pd-events"><caption>{ml.label} averaged only over selected played rounds with that metric. Adjusted totals use the fixed PGA-start zero; category SG is field-relative. Event finish remains the full event result. Expand to inspect selected rounds.</caption><thead><tr><th>Event / course</th><th>Event finish</th><th>Selected rounds</th><th>{ml.label}<small>{ml.unit}</small></th></tr></thead><tbody>{visible.map(e=><Fragment key={e.id}><tr><th scope="row"><button className="pd-expand" aria-expanded={expanded.includes(e.id)} onClick={()=>setExpanded(s=>s.includes(e.id)?s.filter(v=>v!==e.id):[...s,e.id])}><span>{expanded.includes(e.id)?"−":"+"}</span>{e.name}</button><small>{date(e.date)} · {e.tour.toUpperCase()}{e.major?" · Major":""}</small><small>{e.course||"Course unavailable"}</small></th><td>{e.finish??"—"}</td><td>{e.round_data.map(r=>`R${r.round??r.round_num}`).join(", ")}</td><td>{signed(metric==="sg_total"?(finite(eventMetricValue(e,metric))&&finite(anchor)?eventMetricValue(e,metric)!-anchor:null):eventMetricValue(e,metric))}</td></tr>{expanded.includes(e.id)&&<tr className="pd-rounds"><td colSpan={4}><table className="pd-table"><caption>{e.name} · selected rounds; SG categories are field-relative</caption><thead><tr><th>Round</th><th>Date</th><th>Score</th><th>Start gap</th><th>Adjusted total</th><th>OTT</th><th>APP</th><th>ARG</th><th>PUTT</th></tr></thead><tbody>{e.round_data.map((r,i)=><tr key={i}><th>R{r.round??r.round_num}</th><td>{date(r.date)}</td><td>{r.score??"—"}</td><td>{finite((r as ContextRound).strokes_behind_leader_before)?`${(r as ContextRound).strokes_behind_leader_before} back`:"—"}</td><td>{signed(r.sg_basis==="source_adjusted"&&finite(r.sg_total)&&finite(anchor)?r.sg_total-anchor:null)}</td><td>{signed(r.sg_ott)}</td><td>{signed(r.sg_app)}</td><td>{signed(r.sg_arg)}</td><td>{signed(r.sg_putt)}</td></tr>)}</tbody></table></td></tr>}</Fragment>)}</tbody></table></div>
 {!visible.length&&<p className="pd-empty">No events match this slice. Reset the shared filters or choose another round.</p>}
 <div className="pd-pagination"><button disabled={current===0} onClick={()=>setPage(current-1)}>← Previous</button><span>Page {current+1} / {pages}</span><button disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next →</button></div>
 <details className="pd-method"><summary>Data coverage and the provider’s field adjustment</summary><p>The previous “opening-round source field offset” filter was a provider adjustment averaged across R1/R2. It moves field-relative total SG onto the provider’s cross-field adjusted scale. Zero belongs to that provider scale; it is not our fixed PGA benchmark. It is now kept out of the main filters because it is not a clean course-difficulty or player-strength measure.</p><p>Contention is reconstructed using cumulative actual strokes before R3/R4, including prior-round completers who later withdrew. Missing sequences and implausible full-round scores remain unknown. Published history has no explicit holes-completed flag; full-round score/par checks are a conservative proxy, so these are reconstructed positions rather than certified leaderboards.</p><p>Feeder results without published adjusted totals remain visible in the table but cannot enter the adjusted SG histogram. SG categories keep their field-relative baseline. Weather and course-type metadata are not certified for filters yet.</p></details></Panel>;
}
