"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Search, ArrowUpRight, Users, X } from "lucide-react";
import { EmptyState, LoadingState, PageIntro, Panel } from "./components";
import { useDashboardData } from "./data";
import { explainKeyFor, orderEvents, parseExplain, pct, type IndexEvent } from "./explain-rules";
import { PROFILE_AXES, sortProfiles, shortProfileDate, selectWeeklyEvent, matchingInputRun, matchesExplainCheckpoint, matchesInputCheckpoint, savedSkill, playerId, completeRadar, finite, parseCatalog, parseProfile, profileHref, profileKey, profileMatches, radarExtent, radarRadius, sameReference, signedZ, type Archetype, type SavedCheckpoint, type PlayerProfile, type ProfileCatalog, type ProfileEntry } from "./player-profile-rules";
import { checkpoints, runLabel, type DistributionEvent } from "./distributions-rules";
import "./player-profiles.css";
type WeeklyEvent = IndexEvent & DistributionEvent & {player_ids?:number[];latest_key?:string;latest_week_key?:string;runs?:Array<{kind:string;run:string;key:string;as_of:string|null}>};

const COLORS = ["var(--chart-1)", "var(--chart-2)", "var(--chart-3)"];
const LABELS = ["Off the tee", "Approach", "Around green", "Putting", "Accuracy", "Distance"];
function useParams() {
  const read = () => typeof window === "undefined" ? new URLSearchParams() : new URLSearchParams(window.location.search);
  const [params, setParams] = useState(read);
  useEffect(() => { const pop = () => setParams(read()); window.addEventListener("popstate", pop); return () => window.removeEventListener("popstate", pop); }, []);
  const update = (patch: Record<string, string | null>) => { const next = read(); for (const [k,v] of Object.entries(patch)) { if (v) next.set(k,v); else next.delete(k); } window.history.replaceState(null,"",`${window.location.pathname}?${next}${window.location.hash}`); setParams(next); };
  return {params, update};
}
function Photo({player}: {player: ProfileEntry | PlayerProfile}) {
  const p = "identity" in player ? player.identity : player;
  const photo = player.photo;
  const [broken, setBroken] = useState(false);
  const url = photo?.url && /^https:\/\//.test(photo.url) ? photo.url : null;
  const initials = p.name.replace(/,/g," ").split(/\s+/).filter(Boolean).map(w=>w[0]).slice(0,2).join("").toUpperCase();
  // Published, attributed remote photos must retain the initials fallback on failed requests.
  // eslint-disable-next-line @next/next/no-img-element
  return <div className="pp-photo-wrap"><div className="pp-photo">{url && !broken ? <img src={url} alt={p.name} onError={()=>setBroken(true)} loading="lazy" referrerPolicy="no-referrer" /> : <span aria-label={`Initials for ${p.name}`}>{initials}</span>}</div><small>{url && !broken ? <a href={photo?.source && /^https:\/\//.test(photo.source) ? photo.source : url} target="_blank" rel="noreferrer">{photo?.source_name ?? "Photo source"}</a> : "Photo unavailable · initials"}</small></div>;
}
function Radar({profiles}: {profiles: PlayerProfile[]}) {
  const extent = radarExtent(profiles);
  const point = (i: number, r: number) => { const angle = (i*60-90)*Math.PI/180; return [210+Math.cos(angle)*132*r,180+Math.sin(angle)*132*r]; };
  const polygon = (r:number) => PROFILE_AXES.map((_,i)=>point(i,r).join(",")).join(" ");
  return <><svg className="pp-radar" viewBox="0 0 420 365" role="img" aria-label={`Six historical skill axes; zero is the dashed middle ring. ${profiles.map(p=>p.identity.name).join(", ")}. Exact values in table below.`}>
    {[0.25,0.5,0.75,1].map(r=><polygon key={r} points={polygon(r)} fill="none" stroke={r===0.5 ? "var(--muted)" : "var(--line-strong)"} strokeDasharray={r===0.5 ? "5 4" : undefined} />)}
    {PROFILE_AXES.map((key,i)=>{const end=point(i,1), label=point(i,1.24); return <g key={key}><line x1="210" y1="180" x2={end[0]} y2={end[1]} stroke="var(--line)" /><text x={label[0]} y={label[1]} textAnchor="middle" fill="var(--muted-strong)" fontSize="12">{LABELS[i]}</text></g>;})}
    <text x="216" y="112" fill="var(--muted)" fontSize="10">0 Z</text><text x="216" y="47" fill="var(--muted)" fontSize="10">+{extent} Z</text><text x="216" y="180" fill="var(--muted)" fontSize="10">−{extent}</text>
    {profiles.map((p,j)=><g key={playerId(p.identity)}>{completeRadar(p) && <polygon points={PROFILE_AXES.map((key,i)=>point(i,radarRadius(p.radar.find(m=>m.key===key)!.z!,extent)).join(",")).join(" ")} fill={COLORS[j]} fillOpacity="0.09" stroke={COLORS[j]} strokeWidth="2" strokeDasharray={j===1 ? "6 3" : j===2 ? "2 3" : undefined} />}{PROFILE_AXES.map((key,i)=>{const m=p.radar.find(m=>m.key===key); if(!finite(m?.z)) return null; const xy=point(i,radarRadius(m.z,extent));return <circle key={key} cx={xy[0]} cy={xy[1]} r="4" fill={COLORS[j]}><title>{p.identity.name}: {m.label} {signedZ(m.z)} Z</title></circle>;})}</g>)}
  </svg><div className="pp-legend">{profiles.map((p,i)=><span key={playerId(p.identity)}><i style={{background:COLORS[i]}} />{p.identity.name}{!completeRadar(p) && " · partial; points only"}</span>)}</div><p className="pp-muted">Z scores use the same published global reference for every player. Higher is better. The dashed ring is average; negative values sit inside it. Missing axes stay empty.</p></>;
}
function ProfilePanel({entry, catalog, compareIds, update}: {entry:ProfileEntry;catalog:ProfileCatalog;compareIds:string[];update:(p:Record<string,string|null>)=>void}) {
  const [compareQuery,setCompareQuery]=useState("");
  const comparisons=sortProfiles(catalog.players).filter(q=>playerId(q)!==playerId(entry) && !compareIds.includes(playerId(q)) && profileMatches(q,compareQuery)).slice(0,50);
  const main=useDashboardData<unknown>(profileKey(entry.profile_key));
  const first=catalog.players.find(p=>playerId(p)===compareIds[0]); const second=catalog.players.find(p=>playerId(p)===compareIds[1]);
  const a=useDashboardData<unknown>(profileKey(first?.profile_key ?? entry.profile_key)); const b=useDashboardData<unknown>(profileKey(second?.profile_key ?? entry.profile_key));
  const p=parseProfile(main.data,playerId(entry));
  if(main.loading) return <LoadingState label={`Loading ${entry.name}'s historical profile`} />;
  if(main.error || !p) return <EmptyState title="Profile unavailable" detail={main.error ?? "The published shard does not match this player identity."} />;
  const requested=[first ? parseProfile(a.data,playerId(first)):null,second ? parseProfile(b.data,playerId(second)):null].filter((v):v is PlayerProfile=>!!v);
  const profiles=[p,...requested.filter(q=>sameReference(p,q))];
  const incompatible=requested.filter(q=>!sameReference(p,q));
  return <div className="pp-profile"><header className="pp-hero"><Photo key={playerId(entry)} player={p} /><div><span className="eyebrow">Historical player profile</span><h2>{entry.name}</h2><p>{entry.country ?? entry.country_code ?? "Country unavailable"} · {entry.dg_id ? `DataGolf ID ${entry.dg_id}` : `Source identity ${playerId(entry)} · unresolved DataGolf identity`}</p><div className="pp-tags">{(entry.tours ?? []).map(t=><span key={t}>{t.toUpperCase()}</span>)}<span>{p.coverage?.status ?? entry.status} coverage</span></div></div><dl><div><dt>Profile as of</dt><dd title={p.as_of}>{shortProfileDate(p.as_of)}</dd></div><div><dt>Last observation</dt><dd title={entry.last_observation}>{shortProfileDate(entry.last_observation)}</dd></div><div><dt>Rounds observed</dt><dd>{entry.n_rounds ?? "Unavailable"}</dd></div></dl></header>
    <Panel title="The player's shape" eyebrow="Historical traits · standardized axes"><div className="pp-compare"><label>Find a comparison<input aria-label="Search comparison golfers" placeholder="Search all golfers…" value={compareQuery} disabled={compareIds.length>=2} onChange={e=>setCompareQuery(e.target.value)}/></label><label>Compare historical profiles<select aria-label="Add comparison player" value="" disabled={compareIds.length>=2} onChange={e=>update({vs:[...compareIds,e.target.value].join(",")})}><option value="">{compareIds.length>=2 ? "Maximum three profiles" : "Choose a player…"}</option>{comparisons.map(q=><option key={playerId(q)} value={playerId(q)}>{q.name}</option>)}</select></label>{compareIds.map(id=><button key={id} onClick={()=>update({vs:compareIds.filter(q=>q!==id).join(",") || null})}>{catalog.players.find(q=>playerId(q)===id)?.name ?? id}<X size={14}/></button>)}</div>
      {incompatible.length>0 && <p role="status" className="pp-muted">Comparison omitted: reference populations differ for {incompatible.map(q=>q.identity.name).join(", ")}.</p>}{(first && a.loading || second && b.loading) && <p role="status">Loading comparison…</p>}{(first && a.error || second && b.error) && <p role="alert">A comparison profile could not be loaded.</p>}
      <Radar profiles={profiles} /><div className="pp-table-scroll"><table className="pp-table"><caption>Exact historical traits and estimation support</caption><thead><tr><th scope="col">Trait</th><th scope="col">Observed</th><th scope="col">Shrunk estimate</th>{profiles.map(q=><th scope="col" key={playerId(q.identity)}>{q.identity.name} Z</th>)}<th scope="col">Sample / effective</th><th scope="col">Data weight</th></tr></thead><tbody>{PROFILE_AXES.map((key,i)=>{const m=p.radar.find(v=>v.key===key);return <tr key={key}><th scope="row">{m?.label ?? LABELS[i]}<small>{m?.unit ?? ""}</small></th><td>{finite(m?.value)?m.value.toFixed(3):"Unavailable"}</td><td>{finite(m?.estimate)?m.estimate.toFixed(3):"Unavailable"}</td>{profiles.map(q=><td key={playerId(q.identity)}>{signedZ(q.radar.find(v=>v.key===key)?.z)}</td>)}<td>{m?.n ?? "—"} / {finite(m?.n_eff)?m.n_eff.toFixed(1):"—"}</td><td>{finite(m?.shrinkage?.weight_on_data)?pct(m.shrinkage.weight_on_data):"Unavailable"}</td></tr>;})}</tbody></table></div>
      <details className="pp-details"><summary>Reference populations, freshness and shrinkage</summary>{PROFILE_AXES.map(key=>{const r=p.references?.[key],m=p.radar.find(v=>v.key===key);return <p key={key}><b>{m?.label ?? key}:</b> {r ? `${r.population}; ${r.n_players} players, minimum ${r.min_rounds} rounds; mean ${(finite(r.mean) ? r.mean.toFixed(3) : "unavailable")}, SD ${(finite(r.sd) ? r.sd.toFixed(3) : "unavailable")}; reference as of ${r.as_of}.` : "Reference unavailable."} Last observation {m?.last_observation ?? "unavailable"}; prior strength {m?.shrinkage?.prior_rounds ?? "unavailable"} rounds. Reference ID {m?.reference ?? "unavailable"}.</p>;})}</details>
    </Panel><PlayingStyle archetype={p.archetype}/><Panel title="Saved event context"><p className="pp-muted">Event probabilities and course adjustments belong to the saved weekly run.</p>{entry.dg_id && <Link className="pp-link" href={`/weekly-players?player=${entry.dg_id}`}>View saved weekly inputs <ArrowUpRight size={16}/></Link>}</Panel></div>;
}
export function PlayersView() {
  const load=useDashboardData<unknown>("golfprice/player_profiles/index.json"); const catalog=useMemo(()=>parseCatalog(load.data),[load.data]);
  const {params,update}=useParams(); const [query,setQuery]=useState("");const [tour,setTour]=useState("");const [coverage,setCoverage]=useState("");const [catalogPage,setCatalogPage]=useState(0);
  const selected=catalog?.players.find(p=>playerId(p)===params.get("player"));
  const filtered=sortProfiles(catalog?.players ?? []).filter(p=>profileMatches(p,query) && (!tour || p.tours?.includes(tour)) && (!coverage || p.status===coverage));
  const page=Math.min(catalogPage,Math.max(0,Math.ceil(filtered.length/100)-1)); const visible=filtered.slice(page*100,(page+1)*100); const pinned=selected && !visible.some(p=>playerId(p)===playerId(selected)) ? selected : null;
  const ids=[...new Set((params.get("vs") ?? "").split(",").filter(id=>/^(?:[1-9][0-9]*|historical-[a-z0-9]+)$/.test(id) && id!==(selected ? playerId(selected) : null)))].slice(0,2);
  if(load.loading) return <LoadingState label="Loading the published player catalog" />;
  return <div className="pp-page"><PageIntro eyebrow="Players" title="Know the player" description="Search the published golfer universe. Explore historical strengths, sample support and a shared reference population." />{load.error || !catalog ? <EmptyState title="Player profiles have not been published" detail={load.error ?? "Publish a historical profile catalog to make this view available."} /> : <><div className="pp-catalog-controls"><label className="pp-search"><Search size={17}/><input aria-label="Search all golfers" placeholder="Name, country or stable ID…" value={query} onChange={e=>{setQuery(e.target.value);setCatalogPage(0);}}/></label><label>Tour<select value={tour} onChange={e=>{setTour(e.target.value);setCatalogPage(0);}}><option value="">All tours</option>{[...new Set(catalog.players.flatMap(p=>p.tours ?? []))].sort().map(t=><option key={t} value={t}>{t.toUpperCase()}</option>)}</select></label><label>Coverage<select value={coverage} onChange={e=>{setCoverage(e.target.value);setCatalogPage(0);}}><option value="">All coverage</option>{["complete","partial","unavailable"].map(s=><option key={s} value={s}>{s}</option>)}</select></label><span><Users size={16}/>{filtered.length} of {catalog.players.length}</span></div><p className="pp-muted pp-sort-note">Complete coverage first, then partial; most recent observations first within each group. Search always covers the full catalog.</p><div className="pp-layout"><div className="pp-catalog-column">{pinned && <button className="pp-pinned" aria-current="true" onClick={()=>update({player:playerId(pinned)})}><small>Selected player</small><strong>{pinned.name}</strong></button>}<nav className="pp-catalog" aria-label="Player catalog">{visible.map(p=><button key={playerId(p)} aria-current={selected && playerId(selected)===playerId(p) ? "true":undefined} onClick={()=>update({player:playerId(p),vs:null})}><strong>{p.name}</strong><small>{(p.tours ?? []).join(" · ").toUpperCase() || "Tour unavailable"} · {p.status}</small></button>)}{!filtered.length && <p>No golfers match these filters.</p>}</nav><div className="pp-pagination"><button disabled={page===0} onClick={()=>setCatalogPage(page-1)}>Previous</button><span>{filtered.length ? page*100+1 : 0}–{Math.min((page+1)*100,filtered.length)} of {filtered.length}</span><button disabled={(page+1)*100>=filtered.length} onClick={()=>setCatalogPage(page+1)}>Next</button></div></div><div>{selected ? <ProfilePanel key={playerId(selected)} entry={selected} catalog={catalog} compareIds={ids} update={update}/> : <Panel title={params.has("player") ? "Player not in this catalog" : "Choose a golfer"}><p className="pp-muted">{params.has("player") ? "This stable ID has no published profile in this generation. Select a golfer from the catalog." : "Select a golfer to explore six historical traits and their estimation support."}</p></Panel>}</div></div></>}</div>;
}

export function WeeklyPlayersView() {
  const load=useDashboardData<{events?:WeeklyEvent[]}>("golfprice/index.json"); const fields=useDashboardData<{schema_version?:string;fields?:Array<{event_uid:string;player_ids:number[]}>}>("golfprice/player_profiles/fields.json"); const events=orderEvents(load.data?.events ?? []) as WeeklyEvent[];const {params,update}=useParams();const event=selectWeeklyEvent(events,params.get("e"),params.get("player"),fields.data?.schema_version==="player_profiles.fields.v1" ? fields.data.fields : []);
  if(load.loading || (params.get("player") && !params.get("e") && fields.loading)) return <LoadingState label="Loading weekly player events"/>;
  return <div className="pp-page"><PageIntro eyebrow="Week" title="Weekly players" description="The saved model checkpoint: player strengths, adjustments and event probabilities, with links to historical profiles." controls={event && <label className="pp-event" id="weekly-event-picker">Saved event<select value={event.event_uid} onChange={e=>update({e:e.target.value})}>{events.map(e=><option key={e.event_uid} value={e.event_uid}>{e.name ?? e.event_uid} · {e.date_start ?? "date unavailable"}</option>)}</select></label>}/>{!event ? <EmptyState title="No saved weekly runs" detail={load.error ?? "Publish a validated golfprice run to inspect exact player components."}/> : <WeeklyBody key={event.event_uid} event={event as WeeklyEvent} playerId={params.get("player")}/>}</div>;
}
function WeeklyBody({event,playerId}:{event:WeeklyEvent;playerId:string|null}) {
  const choices=checkpoints(event); const [run,setRun]=useState(""); const checkpoint=choices.find(r=>r.run===run); const key=checkpoint?.key ?? explainKeyFor(event); const expected=matchingInputRun(event,checkpoint);
  return <><label className="pp-event">Saved checkpoint<select value={run} onChange={e=>setRun(e.target.value)}><option value="">Current saved checkpoint</option>{choices.map(r=><option key={`${r.kind}_${r.run}`} value={r.run}>{runLabel(r)}</option>)}</select></label><SavedInputs key={run || "current"} dataKey={expected?.key ?? null} expected={expected} playerId={playerId}/><WeeklyExplain key={key} event={event} dataKey={key} expected={expected} playerId={playerId}/></>;
}
function WeeklyExplain({event,dataKey,expected,playerId}:{event:WeeklyEvent;dataKey:string;expected:SavedCheckpoint|null;playerId:string|null}) {
  const load=useDashboardData<unknown>(dataKey);const doc=useMemo(()=>parseExplain(load.data),[load.data]);const [query,setQuery]=useState("");
  if(load.loading) return <LoadingState label="Loading the saved player checkpoint"/>;
  if(load.error || !doc || !matchesExplainCheckpoint(doc,expected)) return <EmptyState title="Saved checkpoint unavailable" detail={load.error ?? "No matching explain document was published for this event."}/>;
  if(playerId && !doc.players.some(p=>String(p.id)===playerId)) return <EmptyState title="Player is not in this saved field" detail="Choose another event above or remove the player filter to inspect this event’s full field."/>;
  const players=doc.players.filter(p=>(!playerId || String(p.id)===playerId) && profileMatches({dg_id:p.id,name:p.name,status:"",profile_key:""},query));const keys=[...new Set(doc.players.flatMap(p=>Object.keys(p.components)))];
  return <><div className="pp-run"><span className="eyebrow">{doc.kind==="live" ? `In play · after round ${doc.after_round}` : "Pre tournament"}</span><strong>{doc.event.name} · {doc.run}</strong><span>Saved {doc.as_of ?? "timestamp unavailable"} · {doc.players.length} players</span></div><Panel title="Saved event components and probabilities" eyebrow="Components: field-relative SG per round · positive increases skill"><label className="pp-search"><Search size={17}/><input aria-label="Search weekly golfers" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a golfer…"/></label>{playerId && <Link href={`/weekly-players?e=${encodeURIComponent(event.event_uid)}`}>Show the full field</Link>}<div className="pp-table-scroll"><table className="pp-table"><caption>Saved {doc.kind} checkpoint {doc.run}. Components are recorded values; no current profile estimates are substituted.</caption><thead><tr><th scope="col">Player</th><th scope="col">Pre-event skill<small>Absolute model SG/round</small></th><th scope="col">Live skill<small>Absolute model SG/round</small></th>{keys.map(key=><th key={key} scope="col">{doc.components_legend[key]?.label ?? key}<small>{doc.components_legend[key]?.group ?? "saved component"}</small></th>)}<th scope="col">B8 live Δ</th><th scope="col">Contention Δ</th><th scope="col">Win</th><th scope="col">Top 10</th><th scope="col">Make cut</th></tr></thead><tbody>{players.map(p=><tr key={p.id}><th scope="row"><Link className="pp-link" href={profileHref(p.id)}>{p.name}<ArrowUpRight size={12}/></Link><small>ID {p.id}</small></th><td>{signedZ(p.mu,3)}</td><td>{signedZ(p.live?.mu_live,3)}</td>{keys.map(key=><td key={key}>{signedZ(p.components[key],3)}</td>)}<td>{signedZ(p.live?.b8_delta,3)}</td><td>{signedZ(p.live?.contention,3)}</td><td>{pct(p.probs.win.model)}</td><td>{pct(p.probs.top_10.model)}</td><td>{doc.event.cut_round === 0 || doc.event.cut_rule === "no cut" ? "No cut" : pct(p.probs.make_cut.model)}</td></tr>)}</tbody></table></div>{!players.length && <p>No players match this selection in the saved event.</p>}<p className="pp-muted">These component values are field-relative; they do not sum to the absolute skill columns. Pre-event skill is the saved baseline; live skill is the updated in-play estimate. B8 and contention shifts are separate. The absolute baseline decomposition is shown in the input table above.</p><details className="pp-details"><summary>What each saved component means</summary>{keys.map(key=><p key={key}><b>{doc.components_legend[key]?.label ?? key}:</b> {doc.components_legend[key]?.meaning ?? "No description was recorded."}</p>)}</details></Panel></>;
}
function SavedInputs({dataKey,expected,playerId}:{dataKey:string|null;expected:SavedCheckpoint|null;playerId:string|null}) {
  if(!dataKey) return <p className="pp-muted">No matching saved model-inputs document is available for this checkpoint.</p>;
  return <SavedInputsBody key={dataKey} dataKey={dataKey} expected={expected} playerId={playerId}/>;
}
function SavedInputsBody({dataKey,expected,playerId}:{dataKey:string;expected:SavedCheckpoint|null;playerId:string|null}) {
  const load=useDashboardData<{players?:Array<{dg_id:number;name:string;challenger?:{breakdown?:{location?:{total?:number};override?:{total?:number}}}}>;as_of?:string;run?:string}>(dataKey);
  if(load.loading) return <LoadingState label="Loading exact saved skill reconciliation"/>;
  if(load.error || !Array.isArray(load.data?.players) || !matchesInputCheckpoint(load.data,expected)) return <p role="status" className="pp-muted">Saved skill reconciliation unavailable: {load.error ?? "input identity, run or timestamp does not match this checkpoint"}.</p>;
  const players=load.data.players.filter(p=>!playerId || String(p.dg_id)===playerId);
  if(playerId && !players.length) return <Panel title="Player absent from this saved field"><p className="pp-muted">This checkpoint has no input row for player ID {playerId}. Choose another event above, or <Link href={`/weekly-players?e=${encodeURIComponent(expected?.event_uid ?? "")}`}>show the full field</Link>.</p></Panel>;
  const keys=[...new Set(players.flatMap(p=>Object.keys(savedSkill(p).families)))];
  return <Panel title="Absolute pre-event skill decomposition" eyebrow="Saved baseline model-inputs · absolute SG per round"><p className="pp-muted">CHL base is the saved pre-location estimate. Families describe the base; they are not added a second time. Location and overrides complete the baseline skill reconciliation. For live checkpoints this table retains the pre-event baseline; updated live skill appears below. Positive residual means baseline skill exceeds the saved component sum.</p><div className="pp-table-scroll"><table className="pp-table"><caption>Exact input source: {dataKey}</caption><thead><tr><th scope="col">Player</th><th scope="col">CHL base</th>{keys.map(k=><th scope="col" key={k}>{k.replaceAll("_"," ")}<small>CHL family · SG/round</small></th>)}<th scope="col">Location</th><th scope="col">Override</th><th scope="col">Component sum</th><th scope="col">Baseline skill</th><th scope="col">Residual</th><th scope="col">Weather by round</th></tr></thead><tbody>{players.map(p=>{const s=savedSkill(p);return <tr key={p.dg_id}><th scope="row"><Link href={profileHref(p.dg_id)}>{p.name}</Link></th><td>{signedZ(s.base,3)}</td>{keys.map(k=><td key={k}>{signedZ(s.families[k],3)}</td>)}<td>{signedZ(p.challenger?.breakdown?.location?.total,3)}</td><td>{signedZ(p.challenger?.breakdown?.override?.total,3)}</td><td>{signedZ(s.sum,3)}</td><td>{signedZ(s.final,3)}</td><td>{signedZ(s.residual,6)}</td><td>{Object.entries(s.weather).map(([r,v])=><small key={r}>{r}: {signedZ(v,3)} SG offset</small>)}{!Object.keys(s.weather).length && "Unavailable"}</td></tr>;})}</tbody></table></div><p className="pp-muted">Weather is separate: these saved offsets increase SG when positive and are excluded from the baseline skill sum. In-play deltas and current event probabilities appear in the checkpoint below.</p></Panel>;
}
function PlayingStyle({archetype}:{archetype:PlayerProfile["archetype"]}) {
  const a:Archetype|null=archetype && typeof archetype==="object" ? archetype : null;
  const traits=[{key:"volatility" as const,label:"Observed volatility",meaning:"Spread of historical rounds; higher means more variable."},{key:"relative_hot_round_upside" as const,label:"Relative hot-round upside",meaning:"Good-round reach above this player’s usual round; higher is more reach."},{key:"tail_balance" as const,label:"Tail balance",meaning:"Positive leans toward upside; negative toward downside. An interval spanning zero is inconclusive."}];
  return <Panel title="Playing style" eyebrow="Provisional descriptive traits · not calibrated predictions"><p>{a?.label ?? (typeof archetype==="string" ? archetype : "No supported archetype has been published.")}</p><p className="pp-muted">{a?.sample?.rounds ?? 0} usable R1/R2 rounds · {a?.sample?.events ?? 0} events · evidence: {a?.reliability?.evidence ?? "unavailable"}</p><div className="pp-trait-grid">{traits.map(t=>{const m=a?.[t.key];return <article key={t.key}><span className="eyebrow">{t.label}</span><strong>{finite(m?.value)?m.value.toFixed(3):"Unavailable"} <small>{m?.unit ?? ""}</small></strong><p>{finite(m?.percentile)?`${m.percentile.toFixed(0)}th percentile · ${m.band ?? "unranked"}`:"Rank unavailable"}{m?.band_uncertain && " · label uncertain"}</p><p className="pp-muted">90% sampling interval: {m?.interval_90?.length===2 ? m.interval_90.map(v=>v.toFixed(3)).join(" to ") : "unavailable"}</p><p className="pp-muted">{t.meaning}</p><small>{m?.reference_players ?? 0} eligible reference players · {finite(m?.shrinkage_weight)?pct(m.shrinkage_weight):"unavailable"} data weight</small></article>;})}</div><p className="pp-muted">{a?.caveat ?? "Historical traits are not validated intrinsic player variance or event forecasts. Relative upside is not absolute playing strength or a chance of winning."}</p><details className="pp-details"><summary>Sample thresholds, reliability and method</summary><p>{a?.reason ?? "No trait method or supported history was published."}</p><p>Ranks are provisional cohort quartiles: low ≤25th percentile; high ≥75th. Volatility needs 30 usable rounds in 10 events; tail traits need 60 rounds in 15 events. Each course-round needs 20 peers and each rank needs 30 eligible reference players. The heuristic shrinkage prior is 40 rounds.</p><p>Intervals use an exploratory 90% event-block bootstrap with fixed peer centers and shrinkage priors; they are sampling intervals, not forecasts.</p><p>Reliability: {a?.reliability?.status ?? "unavailable"}. {a?.reliability?.reason ?? "Verified cut-maker evidence is unavailable."}</p>{a?.notes?.map((n,i)=><p key={i}>{n}</p>)}</details></Panel>;
}
