"use client";

import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownRight, ArrowUpRight, CircleHelp, CloudSun, Info, Search, X } from "lucide-react";
import { useDashboardData } from "./data";
import { EmptyState, LoadingState, PageIntro, Panel } from "./components";
import { orderEvents } from "./explain-rules";
import { checkpoints, runLabel, type DistributionEvent } from "./distributions-rules";
import { betEv, breakEvenDecimal, curveRows, decimalToAmerican, evBreakEvenShift, marketNoVig, normalizePmf, overUnder, parseScoring, prettyName, shiftedOverUnder, type ScoringPlayer } from "./scoring-rules";
import "./scoring.css";

const COLORS = ["var(--chart-1)", "var(--chart-3)", "var(--chart-2)", "var(--chart-4)"];
const fmt = (n: number | null | undefined, d = 2) => n == null || !Number.isFinite(n) ? "—" : n.toFixed(d);
const pct = (n: number | null | undefined, d = 1) => n == null || !Number.isFinite(n) ? "—" : `${(n * 100).toFixed(d)}%`;
const relative = (n: number | null | undefined, digits = 2) => n == null ? "Unavailable" : `${n > 0 ? "+" : ""}${n.toFixed(digits)} strokes`;
const finiteMeta = (v: unknown): v is number => typeof v === "number" && Number.isFinite(v);

export function ScoringView() {
  const index = useDashboardData<{ events: DistributionEvent[] }>("golfprice/index.json");
  const events = orderEvents(index.data?.events ?? []) as DistributionEvent[];
  const [eventId, setEventId] = useState("");
  const event = events.find((e) => e.event_uid === eventId) ?? events[0];
  if (index.loading) return <LoadingState label="Loading scoring checkpoints" />;
  if (index.error || !event) return <EmptyState title="No validated simulations available" detail={index.error ?? "Publish a validated event checkpoint to explore scoring expectations."} />;
  return <>
    <PageIntro eyebrow="Round scoring model" title="What score should we expect?" description="Explore expected strokes, the range of simulated outcomes, what builds the number, and how sensitive it is to a manual market line."
      controls={<label className="score-select">Event<select aria-label="Event" value={event.event_uid} onChange={(e) => setEventId(e.target.value)}>{events.map((e) => <option key={e.event_uid} value={e.event_uid}>{e.tour?.toUpperCase()} · {e.name}</option>)}</select></label>} />
    <ScoringExplorer key={event.event_uid} event={event} />
  </>;
}

function ScoringExplorer({ event }: { event: DistributionEvent }) {
  const runs = checkpoints(event);
  const latest = runs.at(-1);
  const [runKey, setRunKey] = useState(latest?.key ?? event.explain_key ?? "");
  if (!runKey) return <EmptyState title="No validated scoring checkpoint" detail="A scoring expectation will appear after the next successful simulation is published." />;
  const selectedRun = runs.find((r) => r.key === runKey);
  return <>
    <div className="score-controls"><label className="score-select">Simulation checkpoint<select aria-label="Simulation checkpoint" value={runKey} onChange={(e) => setRunKey(e.target.value)}>{runs.length ? runs.map((r) => <option key={r.key} value={r.key}>{runLabel(r)}{r.key === latest?.key ? " · Latest" : ""}</option>) : <option value={runKey}>Latest validated run</option>}</select></label></div>
    {runs.length > 1 && <nav className="score-timeline" aria-label="Event checkpoints">{runs.map((r, i) => <button key={r.key} type="button" aria-current={r.key === runKey ? "step" : undefined} className={r.key === runKey ? "active" : ""} onClick={() => setRunKey(r.key)}><span>{i + 1}</span>{runLabel(r).split(" · ")[0]}<small>{runLabel(r).split(" · ")[1]}</small></button>)}</nav>}
    <Snapshot key={runKey} runKey={runKey} expectedRun={selectedRun?.run ?? null} latest={runKey === latest?.key} />
  </>;
}

function Snapshot({ runKey, expectedRun, latest }: { runKey: string; expectedRun: string | null; latest: boolean }) {
  const source = useDashboardData<unknown>(runKey);
  const scoring = useMemo(() => {
    if (!source.data || typeof source.data !== "object") return null;
    return parseScoring((source.data as Record<string, unknown>).scoring);
  }, [source.data]);
  const [query, setQuery] = useState("");
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const [fieldSelected, setFieldSelected] = useState(true);
  const [curveMode, setCurveMode] = useState<"pmf" | "cdf">("cdf");
  const [scenarioShift, setScenarioShift] = useState(0);
  const [line, setLine] = useState(71.5);
  const [overOdds, setOverOdds] = useState(1.91);
  const [underOdds, setUnderOdds] = useState(1.91);
  if (source.loading) return <LoadingState label="Loading scoring expectation" />;
  if (source.error || !scoring) return <EmptyState title="Scoring expectation unavailable" detail={source.error ?? "This validated checkpoint has no supported scoring block. The page does not infer a score from unrelated finish or market data."} />;
  if (expectedRun !== null && scoring.run_id !== expectedRun) return <EmptyState title="Scoring checkpoint does not match" detail="The scoring block run ID differs from the selected validated checkpoint. This snapshot is hidden until the published source is consistent." />;
  if (scoring.status !== "available") return <EmptyState title="Scoring expectation not published" detail={scoring.source_notes.join(" ") || scoring.baseline.detail || "The checkpoint did not contain enough valid scoring data."} />;
  const validPlayers = scoring.players.filter((p) => p.pmf.length && p.pmf.every(([, prob]) => Number.isFinite(prob)));
  const activePlayers = fieldSelected ? [] : (selectedIds.length ? selectedIds.map((id) => validPlayers.find((p) => p.id === id)).filter((p): p is ScoringPlayer => !!p) : validPlayers.slice(0, 1));
  const chosen = activePlayers[0] ?? null;
  // Field moments are published, but no joint field-average PMF is. Do not manufacture one by averaging marginals.
  const selectedRows = chosen?.pmf ?? [];
  const selectedLabel = chosen ? prettyName(chosen.name) : "Active field average";
  const probs = selectedRows.length ? (scenarioShift ? shiftedOverUnder(selectedRows, line, scenarioShift) : overUnder(selectedRows, line)) : null;
  const noVig = marketNoVig(overOdds, underOdds);
  const allMatches = query ? validPlayers.filter((p) => prettyName(p.name).toLowerCase().includes(query.toLowerCase()) || p.name.toLowerCase().includes(query.toLowerCase())).slice(0, 8) : [];
  const shifts = Array.from({ length: 7 }, (_, i) => scenarioShift + (i - 3) * 0.5);
  const sensitivity = selectedRows.length ? shifts.map((shift) => ({ shift, over: 100 * shiftedOverUnder(selectedRows, line, shift).over, under: 100 * shiftedOverUnder(selectedRows, line, shift).under })) : [];
  const weatherOffsetsUnavailable = scoring.weather.relative_offsets_status === "unavailable";
  const visibleComponents = (chosen?.components ?? []).filter((c) => !(c.key === "weather" && weatherOffsetsUnavailable));
  const maxComponent = Math.max(0.1, ...(visibleComponents.map((c) => Math.abs(c.strokes))), Math.abs(scoring.baseline.arithmetic_residual ?? 0));
  const rawDoc = source.data as Record<string, unknown>;
  const modelMeta = rawDoc.model && typeof rawDoc.model === "object" ? rawDoc.model as Record<string, unknown> : {};
  const asOf = typeof rawDoc.as_of === "string" ? rawDoc.as_of : null;
  const courseCard = rawDoc.course_card && typeof rawDoc.course_card === "object" ? rawDoc.course_card as Record<string, unknown> : {};
  const holeProfile = Array.isArray(courseCard.holes) ? courseCard.holes.filter((h): h is Record<string, unknown> => !!h && typeof h === "object" && typeof (h as Record<string, unknown>).hole === "number" && typeof (h as Record<string, unknown>).par === "number" && typeof (h as Record<string, unknown>).exp === "number").map((h) => ({ hole: h.hole as number, par: h.par as number, exp: h.exp as number })) : [];
  const courseZeroObs = scoring.baseline.median_hole_observations === 0;
  const warnings = [...scoring.confidence.reasons, ...(scoring.weather.status && !/available|applied|fresh|\bok\b|common[_ ]only/i.test(scoring.weather.status) ? [`Weather source status: ${scoring.weather.status}.`] : []), ...(weatherOffsetsUnavailable ? [scoring.weather.relative_offsets_reason ?? "Player-level scoring weather offsets are unavailable; their effect remains in the residual."] : []), ...(scoring.baseline.median_hole_observations == null ? ["Course hole-history depth was not reported."] : [])];
  const weatherDetail = scoring.weather.relative_offsets_reason ?? scoring.weather.label ?? scoring.weather.status ?? (scoring.baseline.common_weather != null ? `Common weather adjustment ${fmt(scoring.baseline.common_weather)} strokes` : "No weather detail published.");
  const mc = chosen ? chosen.sd / Math.sqrt(chosen.n_draws) : scoring.confidence.monte_carlo_se?.field ?? null;
  const mcBasis = chosen ? "player SD ÷ √valid draws" : scoring.confidence.monte_carlo_se?.basis ?? "simulation precision only";
  const pmfs = activePlayers.map((p) => ({ id: p.id, pmf: normalizePmf(p.pmf) }));
  const fieldQuantiles = scoring.field.quantile_curve?.map(([q, score]) => ({ score, quantile: q * 100 })) ?? [];
  const chartRows = fieldSelected ? (curveMode === "cdf" ? fieldQuantiles : []) : curveRows(pmfs, curveMode === "cdf");
  const noVigLean = noVig && probs ? (probs.over - noVig.over) * 100 : null;
  const breakevenOverShift = selectedRows.length ? evBreakEvenShift(selectedRows, line, "over", overOdds) : null;
  const breakevenUnderShift = selectedRows.length ? evBreakEvenShift(selectedRows, line, "under", underOdds) : null;
  const expectedScore = chosen?.mean ?? scoring.field.mean;
  const vsPar = expectedScore != null && scoring.baseline.round_par != null ? expectedScore - scoring.baseline.round_par : null;
  return <div className="score-page">
    <div className="score-context"><span className={latest ? "score-pill latest" : "score-pill"}>{latest ? "Latest validated run" : "Validated checkpoint"}</span><span>Round {scoring.round} · {scoring.run_id}</span><span>{scoring.n_draws.toLocaleString()} score draws</span><span>{scoring.probability_basis === "model" ? "Model probabilities" : scoring.probability_basis}</span><span>{asOf ? `Source as of ${new Date(asOf).toLocaleString()}` : "Source timestamp unavailable"}</span><span>{finiteMeta(modelMeta.n_sims) ? `${Number(modelMeta.n_sims).toLocaleString()} tournament sims` : "Tournament sim count unavailable"}</span><span title={typeof rawDoc.source_sha256 === "string" ? rawDoc.source_sha256 : undefined}>{typeof rawDoc.source_sha256 === "string" ? `Source SHA-256 ${rawDoc.source_sha256.slice(0, 12)}…` : "Source hash unavailable"}</span></div>
    <section className="score-decision" aria-labelledby="score-decision-title">
      <div className="score-decision-main"><span className="score-kicker"><span className="score-pulse" />EXPECTED ROUND SCORE · {selectedLabel}</span><h2 id="score-decision-title">{fmt(expectedScore)} <small>strokes</small></h2><p>{chosen ? `Model average for ${prettyName(chosen.name)} in round ${scoring.round}.` : `Model average across ${scoring.field.players} active players in round ${scoring.round}.`}{vsPar != null ? ` ${Math.abs(vsPar).toFixed(2)} ${vsPar < 0 ? "below" : "above"} par ${scoring.baseline.round_par}.` : ""}</p><div className="score-ci" aria-label="Central 80 percent outcome interval"><span>Central 80% of simulated outcomes</span><b>{fmt(chosen?.p10 ?? scoring.field.p10)} <i>to</i> {fmt(chosen?.p90 ?? scoring.field.p90)}</b><small>Outcome spread from simulation draws</small></div></div>
      <div className="score-confidence"><div className="confidence-icon"><CircleHelp size={19} /></div><span>HOW CONFIDENT IS THE EXPECTED VALUE?</span><strong>Not yet calibrated</strong><p>The conditional mean for this modelled field is separate from the eventual single-round score. Historical coverage has not established true-mean error; the 80% range describes individual outcomes.</p>{mc != null && <div className="score-mc"><span>Monte Carlo precision</span><b>±{fmt(mc, 4)} strokes</b><small>{mcBasis}. Simulation noise only; not uncertainty that the expected value is correct.</small></div>}{noVigLean != null && <div className="score-market-lean"><span>Vs your manual no-vig input</span><b>{Math.abs(noVigLean) < 0.1 ? "Near market" : `${noVigLean > 0 ? "Over" : "Under"} +${Math.abs(noVigLean).toFixed(1)} pp`}</b><small>At line {line} · odds {overOdds}/{underOdds}; this is a comparison, not a recommendation.</small></div>}</div>
    </section>
    {warnings.length > 0 && <aside className="score-alert" role="note"><Info size={17} /><div><b>Read with care</b>{warnings.map((w, i) => <p key={i}>{w}</p>)}</div></aside>}
    {courseZeroObs && <aside className="score-alert score-alert-critical" role="alert"><Info size={17} /><div><b>No historical hole observations in the course baseline</b><p>The exporter reports median hole-history depth as 0. This is a model-input limitation; inspect the hole profile and source notes before interpreting the score.</p></div></aside>}

    <div className="score-kpi-grid"><div><span>Expected score</span><b>{fmt(chosen?.mean ?? scoring.field.mean)}</b><small>Mean of the stored outcomes</small></div><div><span>Median outcome</span><b>{fmt(chosen?.p50 ?? scoring.field.p50)}</b><small>Half of simulated outcomes at or below</small></div><div><span>Outcome SD</span><b>{fmt(chosen?.sd ?? scoring.field.sd)}</b><small>Round-to-round outcome variation</small></div><div><span>Draws supporting player</span><b>{(chosen?.n_draws ?? scoring.n_draws).toLocaleString()}</b><small>Valid outcomes used for this mean</small></div></div>

    <Panel title="Pick a player or stay with the field" eyebrow="Overlay up to four score distributions">
      <div className="score-player-tools"><div className="score-player-chips"><button type="button" className={!fieldSelected && selectedIds.length === 0 ? "selected" : ""} onClick={() => { setFieldSelected(false); setSelectedIds([]); }} aria-pressed={!fieldSelected && selectedIds.length === 0}>Default player</button><button type="button" className={fieldSelected ? "selected" : ""} onClick={() => setFieldSelected(true)} aria-pressed={fieldSelected}>Active field average</button><span className="score-player-active">{fieldSelected ? "Field moments selected" : `${activePlayers.length} of 4 overlay slots`}</span></div><label className="score-search"><Search size={15} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Find and add a player" aria-label="Find and add a player" />{query && <span className="score-search-results" role="group" aria-label="Matching players">{allMatches.map((p) => <button type="button" key={p.id} onClick={() => { setFieldSelected(false); setSelectedIds((prev) => prev.includes(p.id) ? prev : [...prev, p.id].slice(-4)); setQuery(""); }}>{prettyName(p.name)}<small>{fmt(p.mean)} strokes</small></button>)}{!allMatches.length && <em>No matching player.</em>}</span>}</label></div>
      {!fieldSelected && activePlayers.length > 0 && <div className="score-selected-chips">{activePlayers.map((p, i) => <span key={p.id} style={{ "--player-color": COLORS[i] } as React.CSSProperties}><i />{prettyName(p.name)}<button type="button" aria-label={`Remove ${prettyName(p.name)} from overlay`} disabled={activePlayers.length <= 1} onClick={() => setSelectedIds((prev) => (prev.length ? prev : activePlayers.map((x) => x.id)).filter((id) => id !== p.id))}><X size={13} /></button></span>)}</div>}
      <div className="score-player-grid">{validPlayers.slice(0, 4).map((p, i) => <button type="button" key={p.id} className={`score-player-card ${activePlayers.some((x) => x.id === p.id) ? "chosen" : ""}`} aria-pressed={activePlayers.some((x) => x.id === p.id)} onClick={() => { setFieldSelected(false); setSelectedIds((prev) => { const base = prev.length ? prev : activePlayers.map((x) => x.id); return base.includes(p.id) ? (base.length <= 1 ? base : base.filter((id) => id !== p.id)) : [...base, p.id].slice(-4); }); }} style={{ "--player-color": COLORS[i] } as React.CSSProperties}><span className="player-dot" />{prettyName(p.name)}<b>{fmt(p.mean)} <small>strokes</small></b><span>P10 {fmt(p.p10)} · Median {fmt(p.p50)} · P90 {fmt(p.p90)} · Depth {p.data_depth ?? "—"} prior rounds{p.tee_time ? ` · Tee ${p.tee_time}` : ""}</span></button>)}</div>
      <p className="score-footnote">{scoring.field.outcome_label}{scoring.field.active_players_min != null && scoring.field.active_players_max != null ? ` · ${scoring.field.active_players_min}–${scoring.field.active_players_max} active players in each draw` : ""}. Field averages preserve same-draw shared weather. No field-average over/under line or expected value is implied.</p>
    </Panel>

      <div className="score-two-col">
      <Panel title="The full range of outcomes" eyebrow={`${selectedLabel} · exact integer scores`}>
        <div className="score-chart-tools"><div className="score-segments" role="group" aria-label="Score distribution view"><button type="button" disabled={fieldSelected} title={fieldSelected ? "Field averages can be fractional; only a paired-draw quantile curve is available." : undefined} className={curveMode === "pmf" ? "active" : ""} aria-pressed={curveMode === "pmf"} onClick={() => setCurveMode("pmf")}>PMF · exact score</button><button type="button" className={curveMode === "cdf" ? "active" : ""} aria-pressed={curveMode === "cdf"} onClick={() => setCurveMode("cdf")}>{fieldSelected ? "Field quantile curve" : "CDF · score or lower"}</button></div><span>{fieldSelected ? "Paired draw field outcomes" : `${activePlayers.length} player${activePlayers.length === 1 ? "" : "s"} overlaid`}</span></div>
        {chartRows.length ? <><div className="score-chart" role="img" aria-label={`${fieldSelected ? "Paired field quantile curve" : curveMode === "cdf" ? "Cumulative" : "Exact score"} distributions for ${fieldSelected ? "the active field average" : activePlayers.map((p) => prettyName(p.name)).join(", ")}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={chartRows} margin={{ top: 12, right: 16, left: 0, bottom: 8 }}><CartesianGrid vertical={false} stroke="var(--line)" /><XAxis dataKey="score" type="number" domain={["dataMin", "dataMax"]} allowDecimals={!fieldSelected} tick={{ fontSize: 11 }} stroke="var(--muted)" label={{ value: "Strokes", position: "insideBottom", offset: -2, fill: "var(--muted)" }} /><YAxis unit="%" dataKey={fieldSelected ? "quantile" : undefined} domain={curveMode === "cdf" ? [0, 100] : [0, "auto"]} width={45} tick={{ fontSize: 11 }} stroke="var(--muted)" /><Tooltip contentStyle={{ background: "var(--popover)", border: "1px solid var(--line)", borderRadius: 10 }} formatter={(v, key) => [`${Number(v).toFixed(2)}%`, fieldSelected ? "Empirical cumulative share" : activePlayers.find((p) => `p_${p.id}` === String(key)) ? prettyName(activePlayers.find((p) => `p_${p.id}` === String(key))!.name) : String(key)]} labelFormatter={(v) => `${fieldSelected ? "Field score quantile" : curveMode === "cdf" ? "Score ≤" : "Score"} ${v}`} />{fieldSelected ? <Line dataKey="quantile" name="Field quantile" type="monotone" stroke="var(--chart-1)" strokeWidth={2.7} dot={false} isAnimationActive={false} /> : activePlayers.slice(0, 4).map((p, i) => <Line key={p.id} dataKey={`p_${p.id}`} name={prettyName(p.name)} type={curveMode === "cdf" ? "monotone" : "stepAfter"} stroke={COLORS[i]} strokeWidth={2.5} dot={false} isAnimationActive={false} />)}</LineChart></ResponsiveContainer></div>
        <div className="score-chart-legend">{fieldSelected ? <span><i />Paired field mean quantiles · {fieldQuantiles.length} points</span> : activePlayers.map((p, i) => <span key={p.id}><i style={{ background: COLORS[i] }} />{prettyName(p.name)} · mean {fmt(p.mean)}</span>)}</div><p className="score-footnote">{fieldSelected ? "Quantiles come from active-player averages within each shared verified draw, preserving correlation. They are not an integer PMF." : "PMF gives exact stored score probability. CDF gives probability of scoring that integer or lower. Player curves use their own valid outcomes."}</p></> : <EmptyState title={fieldSelected ? "Field curve unavailable" : "Player score distribution unavailable"} detail={fieldSelected ? "This export has field moments but no paired-draw quantile curve. The field average is never reconstructed from player marginals." : "No score distribution is available for this selected player."} />}
      </Panel>
      <Panel title="How this score is built" eyebrow="Stored component arithmetic · strokes">
        {visibleComponents.length ? <div className="score-build">{visibleComponents.map((c) => <div className="score-build-row" key={c.key}><div><span>{c.label}</span><b>{relative(c.strokes)}</b></div><div className="score-build-track"><i style={{ width: `${Math.min(100, Math.abs(c.strokes) / maxComponent * 46)}%`, marginLeft: c.strokes < 0 ? `${50 - Math.min(50, Math.abs(c.strokes) / maxComponent * 46)}%` : "50%", background: c.strokes < 0 ? "var(--positive)" : "var(--warning)" }} /></div>{c.note && <small>{c.note}</small>}</div>)}{scoring.baseline.arithmetic_residual != null && <div className="score-residual"><span>Field-level arithmetic residual</span><b>{relative(scoring.baseline.arithmetic_residual)}</b><small>Applied before player-level residuals; shown for reconciliation, not as a player driver.</small></div>}{chosen?.components.some((c) => c.key === "unexplained_residual") && <p className="score-footnote">Player residual is explicitly included in the published component list to reconcile known inputs with the exact draw mean.</p>}</div> : <EmptyState title="Component breakdown unavailable" detail="The published scoring block has no player component detail for this outcome." />}
        <div className="score-baseline"><span>Baseline inputs</span><div><span>Course score</span><b>{fmt(scoring.baseline.course_score)}</b></div><div><span>Common weather</span><b>{fmt(scoring.baseline.common_weather)}</b></div><div><span>Median hole observations</span><b>{scoring.baseline.median_hole_observations?.toLocaleString() ?? "—"}</b></div><div><span>Baseline provenance</span><b>{scoring.baseline.source ?? "Unavailable"}</b></div>{scoring.baseline.detail && <small>{scoring.baseline.detail}</small>}</div>
      </Panel>
    </div>

    <Panel title="Course profile by hole" eyebrow={holeProfile.length ? `${holeProfile.length} published hole expectations · expected strokes vs par` : "Hole-level course baseline"}>
      {holeProfile.length ? <div className="score-hole-chart" role="img" aria-label="Published course expected strokes relative to par by hole"><ResponsiveContainer width="100%" height="100%"><BarChart data={holeProfile} margin={{ top: 8, right: 8, bottom: 4, left: 0 }}><CartesianGrid vertical={false} stroke="var(--line)" /><XAxis dataKey="hole" interval={0} tick={{ fontSize: 10 }} stroke="var(--muted)" label={{ value: "Hole", position: "insideBottom", offset: -3, fill: "var(--muted)" }} /><YAxis width={40} tick={{ fontSize: 10 }} stroke="var(--muted)" tickFormatter={(v) => Number(v) > 0 ? `+${v}` : String(v)} /><ReferenceLine y={0} stroke="var(--muted)" /><Tooltip contentStyle={{ background: "var(--popover)", border: "1px solid var(--line)", borderRadius: 10 }} formatter={(v) => [`${Number(v) > 0 ? "+" : ""}${Number(v).toFixed(2)} vs par`, "Expected strokes"]} labelFormatter={(h) => `Hole ${h} · par ${holeProfile.find((x) => x.hole === Number(h))?.par ?? "—"}`} /><Bar dataKey="exp" name="Expected strokes vs par" radius={[3, 3, 0, 0]} isAnimationActive={false}>{holeProfile.map((h) => <Cell key={h.hole} fill={h.par === 3 ? "var(--chart-2)" : h.par === 5 ? "var(--chart-3)" : "var(--chart-1)"} />)}</Bar></BarChart></ResponsiveContainer></div> : <EmptyState title="Hole profile unavailable" detail="No hole-level expectation was included in this checkpoint&apos;s explain document." />}<p className="score-footnote">Course profile is a field baseline source diagnostic; it does not attribute this individual player&apos;s score or replace that player&apos;s outcome distribution.</p>
    </Panel>

    <Panel title="What if the market line moved?" eyebrow="Manual player prop scenario">
      <div className="score-market-inputs"><label>Score line<input type="number" step="0.5" value={line} onChange={(e) => setLine(Number(e.target.value))} aria-label="Manual score line" /></label><label>Over odds · decimal<input type="number" step="0.01" min="1.01" value={overOdds} onChange={(e) => setOverOdds(Number(e.target.value))} aria-label="Over decimal odds" /></label><label>Under odds · decimal<input type="number" step="0.01" min="1.01" value={underOdds} onChange={(e) => setUnderOdds(Number(e.target.value))} aria-label="Under decimal odds" /></label><span className="manual-label"><Info size={14} />Manual assumptions</span></div>
      <div className="score-shift-presets"><span>Baseline-shift scenario</span>{[-1, -0.5, 0, 0.5, 1].map((s) => <button key={s} type="button" className={scenarioShift === s ? "active" : ""} aria-pressed={scenarioShift === s} onClick={() => setScenarioShift(s)}>{s > 0 ? "+" : ""}{s.toFixed(1)} strokes</button>)}</div>
      <div className="score-market-grid">{fieldSelected ? <div className="score-market-card model"><span>PLAYER SELECTION REQUIRED</span><p>The field average is the default expected-score view. Select an individual player to compare a manual player over/under prop; no field-average bet line is implied.</p></div> : <><div className="score-market-card model"><span>MODEL · {selectedLabel}</span>{probs ? <><div><b>{pct(probs.over)}</b><small>OVER</small><b>{pct(probs.under)}</b><small>UNDER</small></div><p>{pct(probs.push)} push · {line} strokes · baseline shift {scenarioShift > 0 ? "+" : ""}{scenarioShift.toFixed(1)}</p><small>Fair break-even odds: Over {decimalToAmerican(breakEvenDecimal(probs, "over"))} · Under {decimalToAmerican(breakEvenDecimal(probs, "under"))}</small></> : <p>Player score distribution unavailable.</p>}</div><div className="score-market-card market"><span>MANUAL MARKET INPUTS</span><div><b>{noVig ? pct(noVig.over) : "—"}</b><small>OVER</small><b>{noVig ? pct(noVig.under) : "—"}</b><small>UNDER</small></div><p>Two-way no-vig comparison · over {overOdds || "—"} / under {underOdds || "—"}</p><small>{noVig ? "Proportional normalization; pushes excluded from two-way implied shares." : "Enter decimal odds greater than 1.00 on both sides."}</small></div><div className="score-market-card ev"><span>UNIT-STAKED EXPECTED VALUE</span><div><b>{fmt(probs && betEv(probs, "over", overOdds) != null ? 100 * betEv(probs, "over", overOdds)! : null, 1)}%</b><small>OVER</small><b>{fmt(probs && betEv(probs, "under", underOdds) != null ? 100 * betEv(probs, "under", underOdds)! : null, 1)}%</b><small>UNDER</small></div><p>{probs ? "Includes push probability at zero profit or loss." : "Unavailable without the player PMF."}</p><small>Illustrative arithmetic only; no stake suggestion.</small></div></>}</div>
      <p className="score-footnote">The line and odds are entered by you. The line is not used to create a model expectation. Integer lines can push when the round score equals the line. Scenario shifts linearly translate the score PMF; they are not new simulations.</p>
    </Panel>

    <div className="score-two-col">
      <Panel title="Sensitivity to a score shift" eyebrow="Deterministic PMF translation · no new simulations">
        {sensitivity.length ? <><div className="score-sensitivity-chart" role="img" aria-label={`Over and under model probabilities at score shifts around line ${line}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={sensitivity} margin={{ top: 12, right: 18, left: 0, bottom: 8 }}><CartesianGrid vertical={false} stroke="var(--line)" /><XAxis dataKey="shift" tickFormatter={(v) => `${Number(v) > 0 ? "+" : ""}${v}`} tick={{ fontSize: 10 }} stroke="var(--muted)" label={{ value: "Shift in simulated score distribution (strokes)", position: "insideBottom", offset: -3, fill: "var(--muted)" }} /><YAxis unit="%" domain={[0, 100]} width={45} tick={{ fontSize: 10 }} stroke="var(--muted)" /><Tooltip contentStyle={{ background: "var(--popover)", border: "1px solid var(--line)", borderRadius: 10 }} formatter={(v, name) => [`${Number(v).toFixed(1)}%`, String(name).toUpperCase()]} labelFormatter={(v) => `Distribution shift ${Number(v) > 0 ? "+" : ""}${v} strokes`} /><ReferenceLine x={scenarioShift} stroke="var(--muted)" strokeDasharray="3 4" /><Line dataKey="over" name="Over" stroke="var(--chart-1)" strokeWidth={2.5} dot={{ r: 3 }} isAnimationActive={false} /><Line dataKey="under" name="Under" stroke="var(--chart-3)" strokeWidth={2.5} dot={{ r: 3 }} isAnimationActive={false} /></LineChart></ResponsiveContainer></div>
        <p className="score-footnote">Fractional shifts split probability between adjacent integer scores by linear interpolation. This is a transparent scenario assumption, not a probability that the original model is right or a fresh simulation.</p><div className="score-breakeven-shifts"><span>Shift needed for EV to reach zero</span><b>Over: {breakevenOverShift == null ? "outside ±5 strokes / unavailable" : `${breakevenOverShift > 0 ? "+" : ""}${breakevenOverShift.toFixed(2)} strokes`}</b><b>Under: {breakevenUnderShift == null ? "outside ±5 strokes / unavailable" : `${breakevenUnderShift > 0 ? "+" : ""}${breakevenUnderShift.toFixed(2)} strokes`}</b><small>Uses your current line and decimal odds. Sign shows the required shift to player score outcomes.</small></div></> : <EmptyState title="Joint field sensitivity unavailable" detail="The exported field moments do not include the joint score distribution needed to reprice this scenario." />}
      </Panel>
      <Panel title="Why this expectation?" eyebrow="Published inputs and method">
        <div className="score-explain-list"><div><CloudSun size={17} /><span><b>Weather input</b><small>{weatherDetail}{scoring.weather.source ? ` · source ${scoring.weather.source}` : " · source unavailable"}{scoring.weather.freshness ? ` · fetched/issued ${scoring.weather.freshness}` : ""}</small></span></div><div><Info size={17} /><span><b>Scoring baseline</b><small>{scoring.baseline.source ?? "Source not reported"}{scoring.baseline.round_par != null ? ` · round par ${scoring.baseline.round_par}` : ""}</small></span></div><div><CircleHelp size={17} /><span><b>Simulation method</b><small>{scoring.method} · {scoring.n_draws.toLocaleString()} score draws · {scoring.probability_basis} basis · model {typeof modelMeta.primary_arm === "string" ? modelMeta.primary_arm : "version unavailable"}</small></span></div>{scoring.drivers.map((d) => <div key={d.key}><ArrowUpRight size={17} /><span><b>{d.label}</b><small>Mean score shift {relative(d.mean_score_shift)}</small></span></div>)}</div>
        {scoring.source_notes.length > 0 && <ul className="score-source-notes">{scoring.source_notes.map((n, i) => <li key={i}>{n}</li>)}</ul>}
      </Panel>
    </div>
    <p className="score-disclaimer"><ArrowDownRight size={15} />Expected score is an average across modeled outcomes. The central interval describes outcome variability; it is not a confidence interval for the model mean. Historical forecast calibration is not yet available.</p>
  </div>;
}
